feat(context-menu) adding right click context menu
nteract/archived-desktop-app pull request #1044
Opened 2016-10-20 02:56 UTC by jkornblum

adding electron-context-menu library to project
addresses issue #944 

adds inspect element while electron is in dev mode
adds context aware cut, copy, paste, save image, copy link

2016-10-20 04:00 UTC, captainsafia requested changes
Great stuff, Joshua! Made some comments inline.

2016-10-20 04:00 UTC, captainsafia commented on src/main/index.js
> +
I think it would make more sense to do this instantiation inside the `launch.js` file within the `launch` function so you're only instantiating a context menu if you know a notebook is being successfully loaded.

2016-10-20 21:47 UTC, rgbkrk commented
Thanks for this @jkornblum! I'm looking forward to it.

In order to make linting pass, you'll need to do the require separate from the call:

```js
const initContextMenu = require('electron-context-menu');
initContextMenu();
```

2016-10-20 23:42 UTC, jkornblum commented on src/main/index.js
> +
Okay, I'm pretty new to nteract (and kind of to Electron/JavaScript ha! I'm more C#/Python guy). I've been familiarizing myself with this code base but help me out.

Do we know a notebook successfully loaded in the 'did-finish-load' event listener for webContents? Or should I just throw the init at the top of the launch() function.

2016-10-20 23:47 UTC, rgbkrk commented on src/main/index.js
> +
Welcome! 

It's all good! I too used to be more a Python and C person. The javascript has absorbed me ever since I realized I needed to do more of it to express the ideas I wanted to. :smile:

For this PR, I wouldn't worry about knowing if a notebook successfully loaded. We can't actually know from here without more event handling. I think that's out of scope for this PR. 

Safia wants you to move this function call over to `src/main/launch.js` as well as adapt the way it's called.

2016-10-24 15:01 UTC, jkornblum commented
Okay I've updated the PR with recommended changes.

2016-10-24 15:05 UTC, captainsafia approved these changes

2016-10-24 15:06 UTC, merged

2016-10-24 15:06 UTC, captainsafia commented
So awesome, Joshua! Thanks!

2016-10-24 15:09 UTC, rgbkrk commented
Welcome to the nteract party! 🎉

2016-10-24 15:11 UTC, rgbkrk commented on src/main/launch.js
> +  initContextMenu();
This should move out of the `launch` function itself. It applies to all BrowserWindows and only needs to be run once, after the `require`.

2016-10-24 15:33 UTC, jkornblum commented on src/main/launch.js
> +  initContextMenu();
That's simple, can this PR be reopened or should I submit another PR?

2016-10-24 15:35 UTC, rgbkrk commented on src/main/launch.js
> +  initContextMenu();
D'oh! I made a PR for this in #1062. Feel free to merge that one.