refactor(saveDialog): Simplify remote electron require
nteract/archived-desktop-app pull request #1171
Opened 2016-11-11 00:52 UTC by lgeiger

Remove unnecessary `require('electron')`

2016-11-11 14:23 UTC, rgbkrk requested changes

2016-11-11 14:23 UTC, rgbkrk commented on test/setup.js
> +    }
Missing a comma right here which causes tests to fail.

2016-11-11 14:48 UTC, lgeiger commented on test/setup.js
> +    }
Ooops. Actually the mock is unnecessary right now but it could be helpful for future tests.

2016-11-11 15:13 UTC, rgbkrk approved these changes

2016-11-11 15:16 UTC, merged

2016-11-11 15:32 UTC, lgeiger commented on test/setup.js
> +    }
I should've added a `caution-late-night-PR` label 😂

2016-11-11 16:20 UTC, rgbkrk commented on test/setup.js
> +    }
Heh.

2016-11-28 19:37 UTC, rgbkrk commented
Are there any more like this?

2016-11-28 20:23 UTC, lgeiger commented
> Are there any more like this?

I don't know. Discovered this at random.