Fix execute error
nteract/archived-desktop-app pull request #1203
Opened 2016-11-16 21:20 UTC by jdetle

- [ ] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)
- [ ] My PR title and commit messages are in [conventional-changelog-standard](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md#how-should-i-write-my-commit-messages-and-pr-titles) format.

2016-11-16 21:45 UTC, jdetle commented
Getting an error 
```
 const action$ = ActionsObservable.from([{type: 'EXECUTE_CELL', id: 'id' },
                                  {type: 'EXECUTE_CELL', id: 'id_2' },
                                  {type: 'ABORT_EXECUTION', id: 'id' },
                                  {type: 'EXECUTE_CELL', id: 'id' }]);
```

@rgbkrk, getting an error saying `action$.filter(...).ofType` is not a function, any idea whats going on here?

2016-11-16 21:47 UTC, jdetle commented
https://github.com/redux-observable/redux-observable/blob/master/docs/Troubleshooting.md

2016-11-16 21:49 UTC, rgbkrk commented
> @rgbkrk, getting an error saying action$.filter(...).ofType is not a function, any idea whats going on here?

That sounds like the observable prototype isn't being patched with the filter operator. This tends to happen if two different versions of Rx are installed locally (one for redux-observable and one for our base app). There are ways to work around it, I'd dig into what you have locally though.

2016-11-16 21:52 UTC, jdetle commented
Alright thanks, I'm having issues applying the fix that the redux-observable folks suggest so I'd appreciate any help.

2016-11-16 22:26 UTC, jayphelps commented
Discussed with @jdetle on gitter, but recording here for posterity. The issue is that redux-observable doesn't currently implement its own `ActionsObservable.from` so it inherits it from `Observable.from`, losing the `.ofType` prototype extension. tl;dr Static operators don't currently use the `lift` mechanism like prototype operators do, but we've [been discussing solving that in RxJS](https://github.com/ReactiveX/rxjs/issues/1829).

For this PR, you can just switch to using `ActionsObservable.of`:

```js
const action$ = ActionsObservable.of(
  { type: 'EXECUTE_CELL', id: 'id' },
  { type: 'EXECUTE_CELL', id: 'id_2' },
  { type: 'ABORT_EXECUTION', id: 'id' },
  { type: 'EXECUTE_CELL', id: 'id' }
);

2016-11-16 22:28 UTC, rgbkrk commented
TIL `of` can take more than one argument.

2016-11-16 22:29 UTC, jdetle commented
And it works! Thanks so much @jayphelps.

2016-11-16 22:29 UTC, jayphelps commented
@jdetle you're welcome!

![party](https://media.giphy.com/media/xT8qAY7e9If38xkrIY/giphy.gif)

2016-11-16 22:43 UTC, rgbkrk requested changes

2016-11-16 22:43 UTC, rgbkrk commented on src/notebook/epics/execute.js
> +      error: true,
:+1:

2016-11-16 22:43 UTC, rgbkrk commented on test/renderer/epics/execute-spec.js
> +  const mockShell = Rx.Subject.create(frontendToShell, shellToFrontend);
Good naming here.

However, I'd do this setup and tear down in each `it` block or use a `beforeEach`.

2016-11-17 01:01 UTC, rgbkrk approved these changes

2016-11-17 01:01 UTC, merged

2016-11-17 01:02 UTC, rgbkrk commented
Thanks @captainsafia and @jdetle!