chore(publish): Cleanup github code
nteract/archived-desktop-app pull request #1262
Opened 2016-12-03 03:41 UTC by jdetle

Posting this in an attempt to solicit help. Would like to be able to store the response of `createGistCallback` in `publishNotebookObservable`, but I have no idea to get the id and html_url from the response. Please help me out if you have the time, thanks.

2016-12-03 04:08 UTC, jdetle commented
Gave gistID and gistURL module level scope to fix the problem, everything working now and its objectively cleaner code.

2016-12-04 04:30 UTC, rgbkrk requested changes

2016-12-04 04:30 UTC, rgbkrk commented on src/notebook/epics/github-publish.js
> +let gistURL;
This needs to be in the state tree somewhere, we can't have module-level singletons. Reasons:

* For codebase style, this goes against our flux principles
* For testing, you can't assume that the module is in the same state. Every single function in here now has access to these variables as part of the module closure.
* For modularity reasons -- you can't use this module now to publish multiple gists with one single page app; every single notebook document would have the same gist ID and gist URL

As for what to do, rely on the state tree to set these, even if they're transient data (not in the notebook tree). What was the problem with the metadata field inside the notebook? It's also the one used with @minrk's gist extension.

2016-12-05 03:08 UTC, rgbkrk commented on src/notebook/epics/github-publish.js
> +    observer.next(overwriteMetadata('gist_id', gistID));
Ok, this is better.

I'd walk through the user expectations with this, listing out different scenarios and the events you expect to see.

2016-12-05 03:12 UTC, rgbkrk commented
Cases for an existing gisted notebook:

## Authenticated gist

If the user "owns" the gist, they should be able to publish (and also update the metadata if necessary).

If the user doesn't own the gist they can't publish, yet they could make a new gist (new metadata).

## Unauthenticated gist

Can't ever write back to an unauthenticated gist, have to make a new one (I think...)

2016-12-05 03:13 UTC, rgbkrk commented on src/notebook/epics/github-publish.js
> +// give these module scope to allow overwriting of metadata
Should probably delete this comment.

2016-12-05 03:15 UTC, rgbkrk approved these changes

2016-12-05 18:10 UTC, jdetle commented
Unfortunately this is broken for overwriting gists. Will attempt to fix this after work tonight.

2016-12-05 18:58 UTC, rgbkrk commented
Oh whoop, I thought I merged this. Glad you're revisiting this now. When you get a chance, I'd try describing in Markdown the user and event flows, resulting states, and expectations.

2016-12-06 04:53 UTC, jdetle commented
Need to come to a decision regarding how we want to handle metadata from previous notebooks, but for now I think this is mergeable.

2016-12-06 18:07 UTC, merged