[WIP] Export as PDF
nteract/archived-desktop-app pull request #1271
Opened 2016-12-09 07:49 UTC by jdetle

This works!!! And it looks great. 

TODO:
------
- [ ] Move logic to saving epic.

2016-12-09 21:37 UTC, rgbkrk commented
It's so weird to me that [there is no print role](http://electron.atom.io/docs/api/menu-item/#class-menuitem) for menu items.

I'm guessing there's a print preview when using `contents.print`, perhaps we can provide both options in a reasonably simple way. Does this have to go to an epic or can this menu option only handle the event and take action, since it doesn't change state?

2016-12-09 21:38 UTC, rgbkrk commented
Also... Woohoo! Thank you for tackling this.

2016-12-09 21:43 UTC, jdetle commented
Yeah I guess you're right that it should just be a function in main since it really doesn't do anything with state. Let me play around with that tonight and get back to you. Honestly I think print preview is something to work towards and mess around with but maybe its own PR.

2016-12-09 21:50 UTC, rgbkrk commented
Seems like we still need the state to get the filename, it just doesn't have to dispatch an action.

2016-12-10 01:50 UTC, rgbkrk requested changes

2016-12-10 01:50 UTC, rgbkrk commented on src/notebook/menu.js
> +    state.metadata.get('filename').split('.')[0] : '~/Untitled';
I think we should show a notification if they haven't set the filename by saving. I'd rather they be able to choose where to save it than making a default.

Other related feedback for this filename extraction:

* `something.r.ipynb` would become `something.pdf` - use [`path.basename`](https://nodejs.org/api/path.html#path_path_basename_path_ext) to extract based on `.ipynb` at the end:

```js
> path.basename('something.r.ipynb', '.ipynb') + '.pdf'
'some.file.pdf'
```

* `~` as part of the filename is not a good default on Windows and may not always resolve correctly. If a user misses the notification, we're also overwriting the same file over and over

2016-12-10 01:50 UTC, rgbkrk commented on src/notebook/menu.js
> +          },
Love this extra touch with the notifications to let them open the PDF.

2016-12-10 01:50 UTC, rgbkrk commented on src/notebook/menu.js
> +export function exportPDF(store) {
I would probably write two functions, one that takes the store and one that takes only the filename.

This should be able to stand on its own as a function that prints-to-PDF the current file. The store adapter around it encodes our business/state logic rather than it being part of the `exportPDF` function.

2016-12-10 01:50 UTC, rgbkrk commented on src/notebook/menu.js
> +      if (error_fs) throw error_fs;
Since this is used by an event handler, this error will either not be seen or thrown at a global level. It would be better to show a notification.

2016-12-10 01:53 UTC, rgbkrk commented on src/notebook/menu.js
> +    fs.writeFile(`${filename}.pdf`, data, (error_fs) => {
One thing you may want to do is to have this function accept a callback rather than do the notifications in here (to make it easier to test).


```js
function exportToPDF(filename, cb) {
  ...
  remote.getCurrentWindow().webContents.printToPDF({ printBackground: true }, (error, data) => {
    if (error) {
      cb(error);
    }    
    fs.writeFile(`${filename}.pdf`, data, cb);
```

2016-12-10 01:56 UTC, jdetle commented
Thanks for the very helpful feedback!

2017-01-17 18:18 UTC, rgbkrk commented
This needs a rebase and I think there are remaining TODOs you were looking to. Are you still coming back to this one?

2017-01-17 18:19 UTC, jdetle commented
Yes, I've been putting it off because I'm not sure if I can do a good job on it. I'll take a stab at it tonight and tomorrow and if I cant get it up to par I'll close it and come back to it later.

2017-01-17 18:25 UTC, rgbkrk commented
No problem, I'm just going through open PRs and some issues since we've been doing a fair bit of refactoring and I'm trying to carve out the module exporting for use in a web app version of the notebook.

2017-01-20 02:52 UTC, closed without merging