GitHub refactor
nteract/archived-desktop-app pull request #1283
Opened 2016-12-15 05:06 UTC by jdetle

Churning so hard GitPrime gonna fine me.

2016-12-17 03:17 UTC, jdetle commented
@minrk https://github.com/jdetle/nteract/blob/f36a9b6668c98bf74d4eb3dfd0638bc3cea946f1/src/notebook/epics/github-publish.js#L63-L68 and https://github.com/jdetle/nteract/blob/f36a9b6668c98bf74d4eb3dfd0638bc3cea946f1/src/notebook/epics/github-publish.js#L105-L107 are what would be relevant to updating your extension.

2016-12-17 03:21 UTC, jdetle commented
Weirdness, the actions not getting emitted was fixed by moving complete into the gist callback. I imagine the complete call was getting registered before the observer.next in the callback? ... But that doesn't really make sense if the test was passing... more to be revealed later I guess.

2016-12-18 18:41 UTC, rgbkrk requested changes

2016-12-18 18:41 UTC, rgbkrk commented on src/notebook/actions.js
> +}
👍

2016-12-18 18:41 UTC, rgbkrk commented on src/notebook/epics/github-publish.js
> +    observer.next(overwriteMetadata('gist_id', gistID));
Improved!

2016-12-18 18:41 UTC, rgbkrk commented on src/notebook/epics/github-publish.js
> +          observer.next(deleteMetadata('gist_id'));
Excellent handling.

2016-12-18 18:41 UTC, rgbkrk commented on src/notebook/epics/github-publish.js
> +export function handleGistAction(store, action) {
This swapping of arguments scares me (need to make sure all calls to it are updated). I do prefer this `store, action` ordering you have here as its consistent with our other functions that include the store (which doesn't change, allowing for `bind` and partial usage).

2016-12-18 18:41 UTC, rgbkrk commented on src/notebook/epics/github-publish.js
> +                                   notificationSystem, publishAsUser);
👍

2016-12-18 18:41 UTC, rgbkrk commented on src/notebook/reducers/document.js
> +  },
This is the only segment of code that is not tested, should be a pretty simple one to test since you just verify that the structure conforms to missing the one field in metadata.

2016-12-18 18:41 UTC, rgbkrk commented on test/renderer/epics/github-publish-spec.js
> +    const handleGist = handleGistAction(store, publishAnonymousAction);
Looks like you've updated these appropriately. :smile:

2016-12-18 19:14 UTC, jdetle commented on src/notebook/epics/github-publish.js
> +export function handleGistAction(store, action) {
Great thing about tests, when you change something it breaks a lot of things!

2016-12-19 20:37 UTC, rgbkrk requested changes

2016-12-19 20:37 UTC, rgbkrk commented on src/notebook/reducers/document.js
> +  [constants.DELETE_METADATA]: function deleteMetadata(state, action) {
Good thing there are tests!

You named the constant `DELETE_METADATA_FIELD` in other sections, you'll want to update that here.

2016-12-19 20:37 UTC, rgbkrk commented on test/renderer/reducers/document-spec.js
> +      document: monocellDocument,
To make sure this test is actually doing something, make the initial document state include some metadata.

```js
document: monocellDocument.setIn(['notebook', 'metadata', 'name'], 'something')
```

Hint: this test should fail based on what I noted above about the constants.

2016-12-19 20:57 UTC, rgbkrk approved these changes
Thanks for the rapid turnaround!

2016-12-19 20:57 UTC, jdetle commented
Thanks for the rapid advice! Hope your holidays are going well.

2016-12-19 20:57 UTC, merged