[WIP] refactor(provider): remove Redux logic from Toolbar
nteract/archived-desktop-app pull request #1323
Opened 2017-01-11 05:44 UTC by captainsafia

Parking this here for a minute. 🚗

2017-01-12 21:49 UTC, peggyrayzis requested changes
Looks awesome so far, thanks for tackling this! 😀 Just a couple minor tweaks that should help clear out some of the build errors.

2017-01-12 21:49 UTC, peggyrayzis commented on src/notebook/providers/toolbar.js
> +    this.dropdown.hide();
Everything is looking really great so far! One thing I think we should move to the ToolbarView is the ability to hide the dropdown since it deals with view state vs. application state. The easiest way to accomplish this is to create a method on the view class that hides the dropdown and invokes the function on its props. Then, you can pass that method to the click handler.

2017-01-12 21:49 UTC, peggyrayzis commented on src/notebook/providers/toolbar.js
> +
Adding Flow typing here such as `removeCell: () => void` should get rid of all your covariant Flow errors. I realized that I never added these to my provider (or Flow to the top of my file 😞 ) so I apologize for being unclear. I'll submit a PR to my provider to fix that tonight.

2017-01-12 21:49 UTC, peggyrayzis commented on src/notebook/views/toolbar.js
> +    return renderActionButtons(this.props);
I think you might want renderToolbar here?

2017-01-14 18:44 UTC, peggyrayzis commented on src/notebook/providers/toolbar.js
> +
I fixed my provider with #1335. We should also be able to type Dispatch properly now too 😀

2017-01-16 20:56 UTC, captainsafia commented on src/notebook/views/toolbar.js
> +    return renderActionButtons(this.props);
OMG THIS IS WHY IT WASN'T WORKING! OMG I AM THE WORST PROGRAMMER. OMG WHY?!!? OMG *THANK YOU*!!!

2017-01-16 21:06 UTC, peggyrayzis commented on src/notebook/views/toolbar.js
> +    return renderActionButtons(this.props);
Haha you are definitely not the worst programmer 😝 sometimes a second pair of eyes makes all the difference!

2017-01-16 22:06 UTC, captainsafia commented on src/notebook/providers/toolbar.js
> +    this.dropdown.hide();
Can you elaborate on this a little bit more?

2017-01-16 23:23 UTC, peggyrayzis commented on src/notebook/providers/toolbar.js
> +    this.dropdown.hide();
Sure! 😀 Providers are only concerned with application level state and are connected to the Redux store. Views are unconnected to the store and should only be concerned with view level state isolated to that component (things like toggling a button or in our case, hiding a dropdown). This pattern helps us enforce separation of concerns.

Another reason we can't hide the dropdown on our provider is because we're using refs to invoke methods on the Dropdown component. Refs are destroyed when their children are destroyed, so we have to sync up establishing the ref with ToolbarView's render method instead of ToolbarProvider.

Provider:
```
clearOutputs() {
const { dispatch, id } = this.props;
dispatch(clearOutputs(id));
}
// pass down this method to the view through props
```

View:
```
// define a method called clearOutputs on the class & bind it in the constructor
clearOutputs () {
this.dropdown.hide()
this.props.clearOutputs()
}

render () {
<li onClick={() => this.clearOutputs()} />
}
```

You might want to move all of the content from renderToolbar into the ToolbarView's actual render method since there's no conditional logic. Here, you would want to leave out clearOutputs from the this.props destructuring since we want to invoke the clearOutputs function on the class.

2017-01-17 19:24 UTC, captainsafia commented on src/notebook/providers/toolbar.js
> +    this.dropdown.hide();
Ah! I think I get it! Thanks for the explanation!

2017-02-04 22:00 UTC, jdetle commented
Hi @captainsafia, I made a change in #1403 that will cause a conflict for this PR.

2017-03-20 16:56 UTC, jdetle commented
I'm going to try to finish this off @captainsafia, hope thats okay

2017-03-20 17:11 UTC, captainsafia commented
Go ahead!

2017-03-22 16:06 UTC, jdetle commented
@peggy, This is ready for a review!

2017-03-22 16:35 UTC, peggyrayzis requested changes
Thanks for taking this Toolbar refactor on! We still need to remove hiding the dropdown from the provider before I can merge. The tests look great though 👍

2017-03-22 16:35 UTC, peggyrayzis commented on src/notebook/providers/toolbar.js
> +    dropdown.hide();
The same feedback that I gave to Safia still applies here. We want to control hiding the dropdown on the view, not the provider, because the view is where the ref is initialized. Passing the dropdown in here seems like we're introducing too much of a circular dependency.

Here's the feedback I gave Safia for your reference. Please let me know if anything is unclear, I'd be happy to jump on a quick call if it's confusing. 😀 
<img width="656" alt="toolbar feedback 1" src="https://cloud.githubusercontent.com/assets/18017067/24209052/91b154ac-0efb-11e7-9c8f-a8255e20576f.png">
<img width="640" alt="toolbar feedback 2" src="https://cloud.githubusercontent.com/assets/18017067/24209053/91b24f9c-0efb-11e7-8e9e-cc951ba829e6.png">

2017-03-22 16:40 UTC, jdetle commented on src/notebook/providers/toolbar.js
> +    dropdown.hide();
OH. I get it. Let me see if I can take care of that right quick.

2017-03-22 16:40 UTC, jdetle commented on src/notebook/providers/toolbar.js
> +    dropdown.hide();
Sorry that you had to repeat yourself.

2017-03-22 16:44 UTC, peggyrayzis commented on src/notebook/providers/toolbar.js
> +    dropdown.hide();
No worries! I had to dig around to find my original feedback, GH hides it once you add new commits 😞

2017-03-22 17:17 UTC, jdetle commented
Think I took care of it, thanks @peggyrayzis

2017-03-22 17:24 UTC, peggyrayzis approved these changes
The changes look great! Thanks for making that fix. 🎉

2017-03-22 17:24 UTC, merged

2017-03-22 17:25 UTC, rgbkrk commented
Woo!