Pdf
nteract/archived-desktop-app pull request #1358
Opened 2017-01-20 02:53 UTC by jdetle

Seemed to have deleted and recreated the wrong branch. Reopening here.

2017-01-20 03:56 UTC, jdetle commented
I need to add tests but if anyone wants to check this out its ready for a review. @rgbkrk, @peggyrayzis, @captainsafia, @lgeiger.

2017-01-20 15:04 UTC, peggyrayzis requested changes
Awesome work on this feature!! It looked really cool when you demoed it on Screenhero last night. 😎 One small change regarding error handling and then this should be ready to merge!

2017-01-20 15:04 UTC, peggyrayzis commented on src/notebook/menu.js
> +    .then(() => storeToPDF(store));
At the end of the promise chain, we should catch any errors here with `catch(e => console.error(e))`. You can substitute console.error for however else we handle errors throughout the app.

Maybe we could also display some kind of error message to the user via the notification system that their action was not completed? 🤔

2017-01-22 00:20 UTC, jdetle commented
I have absolutely no idea how to go about testing `export function triggerSaveAsPDF(store) {
  showSaveAsDialog()
    .then(filename =>
      Promise.all(
        [triggerWindowRefresh(store, filename),
          triggerKernelRefresh(store)]
      )
    )
    .then(() => storeToPDF(store))
    .catch(e => store.dispatch({ type: 'error', payload: e.message, error: true }));
}
```
and given that TriggerSaveAs seems to be uncovered as well, I think other people have had the same problem. Any ideas?

2017-01-22 22:30 UTC, jdetle commented
I could make the trigger functions take the functions that call inside as arguments, but I'd rather be able to stub them in the tests. Unfortunately that's not possible to the best of my knowledge.

2017-01-24 03:43 UTC, jdetle commented
Hi @peggyrayzis, are the changes ok?

2017-01-24 04:08 UTC, peggyrayzis commented on src/notebook/menu.js
> +    .catch(e => store.dispatch({ type: 'error', payload: e.message, error: true }));
Nice, that's definitely how you catch an error at the bottom of a promise chain but I'm not sure if that object is what we want to dispatch to Redux. Usually, dispatch takes a function (action creator) that returns an action with a type & payload. Although, maybe redux-observable handles things differently with the epics and I'm missing something here.

Do we have an action creator that triggers an error action? @rgbkrk

2017-01-24 04:21 UTC, jdetle commented on src/notebook/menu.js
> +    .catch(e => store.dispatch({ type: 'error', payload: e.message, error: true }));
I dont think we do, you can search for other instances of the same pattern elsewhere in our codebase. I'd be happy to write up an error action creator and refactor all the instances of code that dispatch an error like this.

2017-01-24 21:46 UTC, peggyrayzis commented on src/notebook/menu.js
> +    .catch(e => store.dispatch({ type: 'error', payload: e.message, error: true }));
No need to refactor, I totally wasn't aware of the error handling middleware. Sorry about that! Since the middleware picks up uppercase 'ERROR', I think all you need to do here is change your action type to ERROR_PDF_SAVED and we should be good to go. 👍

2017-01-25 18:54 UTC, jdetle commented
@peggyrayzis, made that change you requested and squashed the commit :)

2017-01-25 19:01 UTC, peggyrayzis approved these changes

2017-01-25 19:03 UTC, peggyrayzis commented
Awesome! Thanks again for all your work on this feature. :shipit:

2017-01-25 19:04 UTC, merged

2017-01-25 19:04 UTC, rgbkrk commented
Woo!

2017-01-25 19:05 UTC, jdetle commented
Huzzah! Thanks so much for all the help. If any of you find things you'd like to iterate on and improve please let me know and I'll happily work on it.