Resolve relative URLs in markdown cells to notebook directory
nteract/archived-desktop-app pull request #1432
Opened 2017-02-07 23:44 UTC by gnestor

Follow up from https://github.com/nteract/nteract/issues/349

2017-02-08 01:22 UTC, rgbkrk requested changes
This is so good to see the commonmark parser being used really well!

2017-02-08 01:22 UTC, rgbkrk commented on src/notebook/components/cell/markdown-cell.js
> +      }
Neat!

2017-02-08 01:22 UTC, rgbkrk commented on src/notebook/components/cell/markdown-cell.js
> +    const { filename } = this.context.store.getState().metadata.toJS();
We shouldn't be relying on `this.context` in these components. Perhaps we could pass down what the `cwd` is?

2017-02-08 01:22 UTC, rgbkrk commented on src/notebook/components/cell/markdown-cell.js
> +    const { filename } = this.context.store.getState().metadata.toJS();
As in from a top level.

2017-02-08 04:38 UTC, gnestor commented on src/notebook/components/cell/markdown-cell.js
> +    const { filename } = this.context.store.getState().metadata.toJS();
Ya, I couldn't figure out how to access it otherwise. Your `<base>` idea sounds better if I understand it correctly: it's a component that has access to `cwd` among other things and it passes it down to other components via props.

2017-02-08 04:48 UTC, rgbkrk commented on src/notebook/components/cell/markdown-cell.js
> +    const { filename } = this.context.store.getState().metadata.toJS();
It's a native HTML element, not a React component. [`<base>` is an HTML Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) that specific the base URL to use for all relative URLs in a document. With the power of React though, when the filename changes, so would the `<base>` and so would all relative paths.

2017-02-08 05:20 UTC, gnestor commented on src/notebook/components/cell/markdown-cell.js
> +    const { filename } = this.context.store.getState().metadata.toJS();
Ohhhh! Ya, that's perfect except that it messes up relative URLs to nteract assets 🤔

2017-02-08 05:27 UTC, rgbkrk commented on src/notebook/components/cell/markdown-cell.js
> +    const { filename } = this.context.store.getState().metadata.toJS();
Yeah I was thinking that since we're doing webpack anyways we could make sure the base assets are loaded first. The ones that are gunked up in the little prototype I showed was only the theme css (which can change).

2017-02-08 22:15 UTC, gnestor commented on src/notebook/components/cell/markdown-cell.js
> +    const { filename } = this.context.store.getState().metadata.toJS();
I just pushed another commit that breaks the context stuff out into a Base component. I did this yesterday before I realized that `<base>` is an HTML element, so for what it's worth...

2017-02-08 22:18 UTC, rgbkrk commented on src/notebook/components/cell/markdown-cell.js
> +    const { filename } = this.context.store.getState().metadata.toJS();
You had me a bit worried when I saw the commit before your comment.

The component you've added `Base` into is supposed to be a disconnected component, in line with #1288.

2017-02-08 22:20 UTC, rgbkrk commented
Great to see this solution! This component is supposed to be a presentational component and as such should not have access to context - props are intended to be the only API in accordance with #1288. I'd like to solve this either with the `<base>` (and required loading changes) or by passing the `cwd` down through the entire tree (yes, that would be a lot of boilerplate to pass it through).

2017-02-08 22:22 UTC, gnestor commented
> This component is supposed to be a presentational component and as such should not have access to context

I get that, but why does MarkdownCell and others define `contextTypes` then? 

> I'd like to solve this either with the <base>

This is ideal.

2017-02-08 22:23 UTC, rgbkrk commented
> I get that, but why does MarkdownCell and others define contextTypes then?

The cell components are currently open check boxes on that issue. I'd rather not introduce more to refactor when we have other options for doing this in line with the architecture plan.

2017-02-08 22:27 UTC, gnestor commented
Ok I see. Props-only approach is vastly superior 👍

2017-03-21 17:56 UTC, rgbkrk commented
From direct messages, I'd love to see this done with `<base>` so that MarkdownCell can be used without knowledge of `cwd`. It should work like any other relative notebook asset.

2017-03-21 17:56 UTC, rgbkrk commented
https://github.com/nteract/nteract/issues/349#issuecomment-278180910

2017-08-15 22:47 UTC, rgbkrk commented
Closing in favor of #1720.

2017-08-15 22:47 UTC, closed without merging