[WIP] VDOM
nteract/archived-desktop-app pull request #1866
Opened 2017-08-27 22:48 UTC by rgbkrk

Bringing back the vdom mimetype from #1212.

This is (mostly) good to go. Quick demo:

![gametime](https://user-images.githubusercontent.com/836375/29754673-04c127d2-8b58-11e7-88e1-c07e711c40e8.gif)

Problems to fix:

* [ ] On save, for some reason the `children` array is empty. This is completely confusing behavior considering that it's getting into the component when displayed like normal. Initial digging shows this in the state tree, at least while being deserialized. WTF
* [ ] Invalid attributes will completely break the whole notebook, not at the `createElement` stage but at `ReactDOM.render`, which can't be caught in the component (we can use a safelist though).

2017-08-27 22:49 UTC, rgbkrk commented
Branch is worth trying out at least!

2017-08-28 16:09 UTC, rgbkrk commented
Figured it out, object-to-react is mutative.

2017-08-29 18:20 UTC, rgbkrk commented
I've updated the spec here to be:

```js
{
  tagName: string, // Must be an HTML tag
  attributes: Object, // attributes must be valid for setting on the element,
  children: Array<VDOMEl>,
}
```

2017-08-29 19:58 UTC, willingc approved these changes

2017-08-29 20:01 UTC, peggyrayzis requested changes
some minor changes but this looks awesome 🎉

2017-08-29 20:01 UTC, peggyrayzis commented on packages/transform-vdom/src/index.js
> +const cloneDeep = require("lodash").cloneDeep;
`import { cloneDeep } from 'lodash'` to keep it consistent

2017-08-29 20:01 UTC, peggyrayzis commented on packages/transform-vdom/src/index.js
> +  shouldComponentUpdate(nextProps: Props): boolean {
do we need the sCU check since there's only one prop?

2017-08-29 20:01 UTC, peggyrayzis commented on packages/transform-vdom/src/index.js
> +  render(): ?React.Element<any> {
I dont think this will ever be null so we can do `React.Element<*>`

2017-08-29 20:20 UTC, rgbkrk commented on packages/transform-vdom/src/index.js
> +  shouldComponentUpdate(nextProps: Props): boolean {
We don't want this to call the `objectToReact` function repetitively (since I know that our components are not very perf optimized). Seemed like a simple quick check.

2017-08-29 20:22 UTC, peggyrayzis commented on packages/transform-vdom/src/index.js
> +  shouldComponentUpdate(nextProps: Props): boolean {
👍

2017-08-29 20:23 UTC, peggyrayzis approved these changes
thanks for making those changes, I think this is ready to go! 😀

2017-08-29 20:36 UTC, merged