Change hovering logic for cell from JS to CSS
nteract/archived-desktop-app pull request #1975
Opened 2017-10-12 21:21 UTC by aaronraff

- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

In response to #1970

2017-10-12 23:00 UTC, rgbkrk approved these changes
Awesome, thank you.

2017-10-12 23:00 UTC, rgbkrk commented on packages/desktop/src/notebook/components/cell/cell.js
> +        <Toolbar type={type} cell={cell} id={this.props.id} />
👍

2017-10-12 23:00 UTC, rgbkrk commented on packages/desktop/src/notebook/main.css
> +  display: block;
There we go, this is great!

2017-10-12 23:02 UTC, rgbkrk requested changes

2017-10-12 23:02 UTC, rgbkrk commented on packages/desktop/src/notebook/components/cell/cell.js
>  export class Cell extends React.PureComponent<CellProps, State> {
There's a current flow error here, you'll want to set this to `React.PureComponent<CellProps, *>`

2017-10-12 23:38 UTC, rgbkrk commented
Tried this out locally, it _also_ fixes an outstanding bug where you couldn't click menu items further down. 🙇

2017-10-12 23:40 UTC, aaronraff commented on packages/desktop/src/notebook/components/cell/cell.js
>  export class Cell extends React.PureComponent<CellProps, State> {
Just committed this change, thanks for pointing that out! I'm still pretty new to Flow.

2017-10-12 23:58 UTC, rgbkrk approved these changes

2017-10-12 23:58 UTC, merged

2017-10-12 23:58 UTC, rgbkrk commented
This is fantastic, I can't wait for this to go in the next release!

2017-10-13 00:00 UTC, aaronraff commented
I'm happy that I could help out, I'm hoping to contribute more in the future!

2017-10-13 00:04 UTC, rgbkrk commented
Welcome to the nteract party! 🎉

2017-10-13 00:14 UTC, rgbkrk commented
Great, we have much ahead. If you want a next issue to tackle, the dropdown menu could use a fix:

![oopsy-under-menu](https://user-images.githubusercontent.com/836375/31524751-85d644ce-af70-11e7-9224-9a164946a918.gif)

It's a little better than before, where it was completely unclickable because of the cells underneath hijacking it via that mouse handler. Now at least I think there's just a bit more CSS to get it right.

2017-10-13 00:25 UTC, aaronraff commented
I will take a look at that! I'm also thinking that a little CSS will do the trick.

2017-10-13 02:07 UTC, aaronraff commented
Took a look at the dropdown menu bug here: #1978