[WIP] Notebook App rendering performance improvements
nteract/archived-desktop-app pull request #2402
Opened 2018-01-21 00:54 UTC by rgbkrk

Quick stab at #2394 and #2362 (and likely others).

master | PR
----|---
![master](https://user-images.githubusercontent.com/836375/35189574-ebc86480-fe01-11e7-8c84-39fef2be601d.gif) | ![pr](https://user-images.githubusercontent.com/836375/35189576-fab58766-fe01-11e7-9c95-02c67348eb95.gif)

I've got some cleanup to do here. Generally I think this could be a lot better. One idea I've had is to move the current global level keybindings (for running / focusing cells) to a separate keybinding component or even just deferring them to our codemirror component.

2018-01-21 01:02 UTC, rgbkrk commented on applications/notebook-on-next/pages/edit.js
> +  return toJS(emptyNotebook);
Reminder to myself that I have to return this file back to how I found it. 😉

2018-01-21 01:03 UTC, rgbkrk commented on packages/core/src/actionTypes.js
> +};
This brings _back_ `EXECUTE_CELL`, which is requesting that we execute a cell with a given ID. This helps us not have to have the cells and their contents bound to actions that will cause cell execution -- they should only have to have the cell ID.

2018-01-21 01:05 UTC, rgbkrk commented on packages/core/src/epics/execute.js
> +          const source = state.getIn(["document", "cellMap", id, "source"], "");
I should probably add a comment in here that we create create the execute request based on the source of the ID from the `EXECUTE_CELL` action.

2018-01-21 01:09 UTC, rgbkrk commented on packages/core/src/providers/notebook-app.js
> -    models: state.comms.get("models"),
The more I was able to take out of our top level component here, the better it got.

2018-01-21 01:10 UTC, rgbkrk commented on packages/core/src/providers/notebook-app.js
> +      // Couldn't focusNextCell just do it, no need to have this here
Clarification on this comment, as well as a todo for me:

There should be a way to dispatch something like `focusTheCellAfterTheCurrentFocusedCell`

2018-01-21 01:11 UTC, rgbkrk commented on packages/core/src/providers/notebook-app.js
> +    this.context.store.dispatch(executeCell(id));
Just the same, we should be able to run `executeFocusedCell`.

2018-01-21 01:13 UTC, rgbkrk commented on packages/core/src/providers/notebook-app.js
> +    const id = this.props.cellFocused;
Can't merge until the functionality here is brought back. I tore it out to reduce how much information the top level notebook was getting so I could get the nice update highlighting. 😄

2018-01-21 17:51 UTC, rgbkrk commented on packages/core/src/providers/notebook-app.js
> -    models: state.comms.get("models"),
Thinking about this one in particular, I think the transforms could/should opt in to the models via `contextTypes`. Only model-debug is using this currently, so I think that's a fine assumption while we carve this out.

2018-01-21 21:40 UTC, rgbkrk commented
Alright! This should now pass and is ready for review!

2018-01-22 16:13 UTC, theengineear commented on packages/core/__tests__/epics/execute-spec.js
> +  test.only("Informs about disconnected kernels, allows reconnection", done => {
⚡️ 💀

2018-01-22 16:17 UTC, theengineear commented on packages/core/src/components/toolbar.js
> +export type ToolbarProps = {|
Does `declare` make the type available globally or something?

2018-01-22 16:18 UTC, theengineear commented on packages/core/src/epics/execute.js
> +          throw new Error("attempted to execute without an id");
If this just throws in here, why do we allow `id?: string` in the type defs?

2018-01-22 16:22 UTC, theengineear commented on packages/core/src/providers/notebook-app.js
> +          <React.Fragment>
👌

2018-01-22 16:25 UTC, theengineear commented on packages/core/src/providers/toolbar.js
> +import * as React from "react";
🐄 isn't the canonical import `import React from "react"`?

2018-01-22 16:26 UTC, theengineear commented on packages/core/src/providers/toolbar.js
> -    dispatch(executeCell(this.props.id, this.props.cell.get("source")));
🎉

2018-01-22 16:27 UTC, theengineear requested changes
Just un-skip that test. Otherwise, looking great!

2018-01-22 16:35 UTC, rgbkrk commented on packages/core/src/providers/toolbar.js
> +import * as React from "react";
From the [flow docs on React](https://flow.org/en/docs/react/components/)

> Note: We import React as a namespace here with import * as React from 'react' instead of as a default with import React from 'react'. When importing React as an ES module you may use either style, but importing as a namespace gives you access to React’s utility types.

Most of the code base is this way as well and occurred on some combo of React 16 and a more recent flow release.

2018-01-22 16:38 UTC, rgbkrk commented on packages/core/src/epics/execute.js
> +          throw new Error("attempted to execute without an id");
The `EXECUTE_FOCUSED_CELL` action has no id, and relies on what's in the store for the current focused cell.  If for some reason a cell is not focused and they hit shift-enter, I figured this should be thrown (and caught in the epic as `catchError` (not in the diff here, it's in the epic much lower).

2018-01-22 16:39 UTC, rgbkrk commented on packages/core/src/components/toolbar.js
> +export type ToolbarProps = {|
You know, I'm not sure. I just switched this to export so I could explicitly use it in the provider component.

2018-01-22 16:41 UTC, rgbkrk commented on packages/core/__tests__/epics/execute-spec.js
> +  test.only("Informs about disconnected kernels, allows reconnection", done => {
Whoops!

2018-01-22 16:57 UTC, rgbkrk commented
Fixed up the tests, now to watch CI run. 👁 👁

2018-01-22 17:06 UTC, theengineear approved these changes

2018-01-22 17:11 UTC, theengineear commented on packages/core/src/providers/toolbar.js
> +import * as React from "react";
ah, awesome. thanks! that's really good to know. i'm positive that saved me like at least 10 minutes down the road somewhere 😛

2018-01-22 17:12 UTC, merged