feat: add help/about to web menu.
nteract/archived-desktop-app pull request #2447
Opened 2018-01-29 21:51 UTC by theengineear

First pass at the about menu. I didn't want to get too far into it so it's pretty minimal / uninformative... I could use some help understanding the rest of the information that needs to make its way into this menu.

<img width="938" alt="screen shot 2018-01-29 at 1 50 46 pm" src="https://user-images.githubusercontent.com/6611546/35536343-6fdc47f0-04fb-11e8-8eb2-7dc66c9ce0e7.png">

2018-01-29 21:53 UTC, theengineear commented
Related https://github.com/nteract/nteract/issues/2446

This component now has to store state, which seems unnecessary. Had I gone with the longer approach of creating an actionType/action/reducer/ControllerComponent setup, we could really have this in isolation. I.e., the action would be the only thing coupling the menu to the modal... which could potentially be cleaner. I think this will work for now though.

Note, reused bits of our set of css variables where I could in the modal css.

2018-01-29 22:05 UTC, rgbkrk commented on packages/core/src/components/notebook-menu/about-modal.js
> +              <p>You are using an Nteract-rendered notebook on Jupyter.</p>
We lowercase "nteract".

2018-01-29 22:06 UTC, rgbkrk commented on packages/core/src/components/notebook-menu/styles.js
> +  }
Oh did it actually let you use `@media` queries? I thought for sure these fell under the "no nested" category. 👍 🎉

2018-01-29 22:07 UTC, theengineear commented on packages/core/src/components/notebook-menu/about-modal.js
> +              <p>You are using an Nteract-rendered notebook on Jupyter.</p>
😬 shame.

2018-01-29 22:08 UTC, theengineear commented on packages/core/src/components/notebook-menu/styles.js
> +  }
nah, this is totally normal CSS, the bug is when you have a newline above a media query for some reason. it seems to flake on that parse. but yah, seems to work just fine 🎉

2018-01-29 22:08 UTC, rgbkrk commented
> Had I gone with the longer approach of creating an actionType/action/reducer/ControllerComponent setup, we could really have this in isolation.

That's totally fine if you want to do that.

2018-01-29 22:39 UTC, rgbkrk commented on packages/core/src/components/notebook-menu/about-modal.js
> +    if (this.overlay && event.target === this.overlay) {
I _think_ if you use `currentTarget` and separate the two divs here so they're not nested you can go without the `ref`.

2018-01-29 22:41 UTC, theengineear commented on packages/core/src/components/notebook-menu/about-modal.js
> +    if (this.overlay && event.target === this.overlay) {
ah, yup, totally right 👍

2018-01-30 04:39 UTC, theengineear commented
@rgbkrk  ⏪ ⏹ ▶️ OK, re-implemented with a `ModalController`.

2018-01-30 16:31 UTC, rgbkrk commented on packages/core/src/components/modal-controller/about-modal.js
> +
For eslint, you're going to have to set:

```
/* eslint jsx-a11y/no-static-element-interactions: 0 */
/* eslint jsx-a11y/click-events-have-key-events: 0 */
/* eslint jsx-a11y/no-noninteractive-element-interactions: 0 */
```

Since there's a click event on a div here.

2018-01-30 16:32 UTC, rgbkrk requested changes

2018-01-30 16:32 UTC, rgbkrk commented on packages/core/src/components/modal-controller/about-modal.js
> +
For eslint, you're going to have to set:

```
/* eslint jsx-a11y/no-static-element-interactions: 0 */
/* eslint jsx-a11y/click-events-have-key-events: 0 */
/* eslint jsx-a11y/no-noninteractive-element-interactions: 0 */
```

Since there's a click event on a div here.

2018-01-30 17:16 UTC, theengineear commented
@rgbkrk, your comments made me realize I skipped some corners 😓. Now we:

1. allow escape-key-exit from the modal
2. have a real `dialog` (yay new html tags)

2018-01-30 17:16 UTC, theengineear commented
I like those `eslint` rules! Super handy!

2018-01-30 19:21 UTC, rgbkrk commented
Oh hey that's even better since the linter prompted better a11y conformance. :smile:

2018-01-30 19:22 UTC, rgbkrk commented on packages/core/src/components/modal-controller/about-modal.js
> +/* eslint jsx-a11y/no-static-element-interactions: 0 */
Superb TODOs for the eslint ignores. 😄

2018-01-30 19:23 UTC, rgbkrk approved these changes

2018-01-30 19:23 UTC, rgbkrk commented on packages/core/src/components/modal-controller/about-modal.js
> +          <dialog tabIndex={0} className="modal--content" ref={focusOnRender}>
👍

2018-01-30 19:23 UTC, merged