testing-the-water
nteract/archived-desktop-app pull request #2454
Opened 2018-01-31 21:10 UTC by theengineear

Just playing around a little bit to provide a richer styling framework via css properties.

2018-01-31 21:11 UTC, theengineear commented on applications/jupyter-extension/nteract_on_jupyter/index.js
> +            <Styles>
We wrap our components in this new provider (lots of wrappers).

2018-01-31 21:11 UTC, theengineear commented on applications/jupyter-extension/nteract_on_jupyter/styles.js
> +const styles = `
This file is auto-generated (can be cleaned up a bit).

2018-01-31 21:14 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/styles.js
> +  --nt-font-family-mono: courier;
This could probably be `'Source Code Pro', courier`.

2018-01-31 21:14 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/styles.js
> +  --nt-z-index-notification: 200;
😄

2018-01-31 21:17 UTC, rgbkrk commented on packages/core/src/providers/styles.js
> +        <style dangerouslySetInnerHTML={{ __html: styles }} />
I've got a funny feeling that you have to encode `styles` when this is used in any server side rendered setup... I can't recall if/where that came up.

2018-01-31 21:18 UTC, rgbkrk commented on packages/styles/src/config.json
> +                "mono": "courier"
Oh I suppose this is where you'd set the mono to `Source Code Pro`.

2018-01-31 21:18 UTC, rgbkrk commented on packages/styles/src/config.json
> +                "modal": 300
😄

2018-01-31 21:18 UTC, rgbkrk approved these changes
Colors!!! 🖍🎨🌈

2018-01-31 21:19 UTC, theengineear commented on packages/styles/src/config.json
> +{
This is the main file that we use to construct our theme.

2018-01-31 21:19 UTC, theengineear commented on packages/styles/src/variables.json
> +[
For validation and programmatic access, we export all the available variables.

2018-01-31 21:21 UTC, theengineear commented on packages/core/src/providers/styles.js
> +        <style dangerouslySetInnerHTML={{ __html: styles }} />
^^ i'm just copying how this was setup in `notebook-app.js`

2018-01-31 21:21 UTC, theengineear commented on packages/core/src/providers/styles.js
> +        <style dangerouslySetInnerHTML={{ __html: styles }} />
but I think there's room for experimentation here.

2018-01-31 21:21 UTC, theengineear commented on packages/styles/src/config.json
> +                "mono": "courier"
👌

2018-01-31 21:21 UTC, rgbkrk commented on packages/core/src/providers/styles.js
> +        <style dangerouslySetInnerHTML={{ __html: styles }} />
ooooooh maybe that wasn't the weird case then

2018-01-31 21:22 UTC, theengineear commented on packages/styles/src/declarations.json
> +  ],
And, here's a clear way to re-create the actual css files (an array, since that's how css works)

2018-02-02 00:46 UTC, theengineear commented
@rgbkrk Might be worth your taking a gander at this point. I need to resolve conflicts and such, but I think this is finally in a stable place.

2018-02-02 00:50 UTC, rgbkrk commented
Ok cool, taking a look now.

2018-02-02 01:11 UTC, rgbkrk requested changes
This is so super to have outlined so well. It'll be much easier to build new UI elements with these primitives and know how to work with them semantically.

2018-02-02 01:11 UTC, rgbkrk commented on applications/desktop/src/notebook/index.js
> +              color: var(--theme-app-fg);
Thanks for making sure desktop gets that base config. 😄

2018-02-02 01:11 UTC, rgbkrk commented on applications/desktop/static/index.html
> +        background: var(--theme-cell-bg, white) !important;
I like that semantically it's `theme` first so I can read it as being a theme-able property. 👍

2018-02-02 01:11 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/index.js
> +            <Styles>
Could probably delete the `div` above this I assume. Also, since the styles don't need the `Provider`, could they go one level above the provider?

2018-02-02 01:11 UTC, rgbkrk commented on packages/core/src/components/index.js
> +              background: var(--theme-cell-output-bg);
should probably have the `white` fallback here, as one of the core components that are style only.

2018-02-02 01:11 UTC, rgbkrk commented on packages/core/src/components/index.js
> +            color: var(--theme-cell-prompt-fg);
🙇  Thank you for switching this to the right name, `prompt` 🙏 . Probably need to include the fallback here as well (of `black`).

2018-02-02 01:11 UTC, rgbkrk commented on packages/core/src/components/index.js
> +            background-color: var(--theme-cell-prompt-bg);
Fallback of `#fafafa` here

2018-02-02 01:11 UTC, rgbkrk commented on packages/core/src/components/index.js
> +            background-color: var(--theme-cell-input-bg);
Fallback of `#fafafa` here

2018-02-02 01:11 UTC, rgbkrk commented on packages/core/src/components/index.js
> +          background: var(--theme-cell-bg);
This is likely the _only_ file that I'll nitpick on having the defaults, only because these are the cell building block components you should be able to start working with, without having to have the `Style` provider.

2018-02-02 01:11 UTC, rgbkrk commented on packages/core/src/themes/dark.js
> +  --theme-primary-fg-focus: var(--theme-app-fg);
Superb!

2018-02-02 01:11 UTC, rgbkrk commented on packages/styles/package.json
> +    "build:pre": "npm run build:styles && npm run build:copy-files",
In adopting package.json scripts, if you've got `pre` steps you should prefix the command you want to happen first like this:

```
"prebuild": "npm run build:clean && npm run build:styles && npm run build:copy-files"
```

npm will then run that before `build`.

2018-02-02 01:11 UTC, rgbkrk commented on packages/styles/package.json
> +    "lib"
Is `build` only a staging directory and `lib` where the final assets go when published?

2018-02-02 01:11 UTC, rgbkrk commented on packages/styles/src/config.json
> +{
Now this is nice and easy to read, structure wise.

2018-02-02 01:11 UTC, rgbkrk commented on packages/styles/src/config.json
> +                "mono": "courier"
Still want that `Source Code Pro` here. 😉

2018-02-02 01:11 UTC, rgbkrk commented on packages/styles/README.md
> +# nteract styles
What's the basic usage story here?

For fonts, we probably want to give the guidance of using:

```html
<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Source+Sans+Pro|Source+Serif+Pro" rel="stylesheet">
```

Though we could always include the import in our base:

```css
@import url('https://fonts.googleapis.com/css?family=Source+Code+Pro|Source+Sans+Pro|Source+Serif+Pro');
```

For desktop we'll still have to go with our packaged version.

2018-02-02 01:14 UTC, theengineear commented on applications/desktop/static/index.html
> +        background: var(--theme-cell-bg, white) !important;
^^ Yup, that's definitely the intention there 🎉

2018-02-02 01:14 UTC, rgbkrk commented on packages/styles/README.md
> +# nteract styles
Errrr actually I think these need to be:

```html
<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700,900|Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
```

and

```css
@import url('https://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700,900|Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i');
```

so we have the full range on Source Code Pro and Source Sans Pro

2018-02-02 01:16 UTC, theengineear commented on packages/styles/package.json
> +    "lib"
Yah. Exactly. Guidance is welcome here. It's definitely a bit of an odd package setup.

2018-02-02 16:40 UTC, rgbkrk commented
Something we should probably look into for our own ANSI coloring (ours comes via `anser`): https://github.com/jupyterlab/jupyterlab/issues/3773

I really love the soft palette that the classic notebook has currently:

<img width="1114" alt="screen shot 2018-02-02 at 8 37 16 am" src="https://user-images.githubusercontent.com/836375/35744124-5a923b60-07f4-11e8-8351-ede12f8b28f2.png">

vs. our current style:

<img width="466" alt="screen shot 2018-02-02 at 8 38 37 am" src="https://user-images.githubusercontent.com/836375/35744218-a10e905c-07f4-11e8-8f85-757352dc9d2f.png">

Those probably _do_ have to be part of our theme setup, though I think are out of scope for this PR.

2018-02-03 00:37 UTC, theengineear commented on applications/jupyter-extension/nteract_on_jupyter/index.js
> +            <Styles>
That didn't work, but just using a `React.Fragment` works fine to get rid of the div.

2018-02-03 00:45 UTC, theengineear commented on packages/styles/package.json
> +    "build:pre": "npm run build:styles && npm run build:copy-files",
Ah, I'll fix this, it's really just a relic of the repo I basically ripped it from.

2018-02-03 00:49 UTC, theengineear commented
>Those probably do have to be part of our theme setup, though I think are out of scope for this PR.

Yah, agreed and agreed :)

2018-02-03 01:22 UTC, theengineear commented
Hrm... @rgbkrk i just rebased on master and now I'm getting some build errors. I might have to circle back and ping you for help on it.

2018-02-03 01:26 UTC, rgbkrk commented
At least for Circle CI, it looks like you need to update the snapshots.

For your local copy, you may need to do a `git clean -xfd && npm i` because I upgraded `lerna`.

2018-02-05 02:32 UTC, theengineear commented
Ah, yup, `git clean -xfd && npm i` did it for me. Thanks!

2018-02-05 16:58 UTC, rgbkrk commented
The current CI error is not your fault (at least, not necessarily), it's due to the old uglify in the next.js apps. It usually happens when a dependency is not transpiled.

2018-02-05 19:20 UTC, rgbkrk approved these changes

2018-02-05 19:20 UTC, merged