More selectors
nteract/archived-desktop-app pull request #2500
Opened 2018-02-07 19:49 UTC by theengineear

[WIP --> 100% not tested yet!]

Jumping on the selectors train! I want to start moving state around, but I won't be confident about doing that until we centralize access with these selectors.

Couple questions:

1. naming: holy `getCurrent*`, batman! It's a little wordy! Maybe `current` should be the default thing we assume to be getting when we're using selectors.
2. `notificationStystem` stuff: not touching it, it's like an object with methods on it? I'm just going to assume we're not moving that :0
3. putting selectors to work: since we're memoizing, we might as well make selectors that do all the work for us! One example here is the `getCurrentCodeCellIdsBelow` (i know, a mouthful...). you're on board for more of the same, right?
4. In general, we should try and keep selectors as specific as possible. The more general they are, the less we can change state! I.e., selectors should be a black box. We should never return hunks of state that we think we'd want to refactor the internals of. Ya?

2018-02-07 19:59 UTC, rgbkrk commented
> naming: holy `getCurrent*`, batman! It's a little wordy! Maybe `current` should be the default thing we assume to be getting when we're using selectors.

`current*` is way better than `getCurrent*`, especially since every selector is a `get*`.

2018-02-07 20:05 UTC, rgbkrk commented on applications/desktop/src/notebook/epics/github-publish.js
> +import * as selectors from "@nterat/core/selectors";
`from "@nteract/core/selectors"`

2018-02-07 20:10 UTC, rgbkrk commented on applications/desktop/src/notebook/epics/github-publish.js
> +        if (githubUsername !== (res.data.login || undefined)) {
solid cleanups in here

2018-02-07 21:23 UTC, theengineear commented on applications/desktop/src/notebook/epics/github-publish.js
> +import * as selectors from "@nterat/core/selectors";
🤣

2018-02-07 21:23 UTC, theengineear commented
>current* is way better than getCurrent*, especially since every selector is a get*.

Cool. Accepted 😎.

2018-02-08 00:04 UTC, rgbkrk requested changes

2018-02-08 00:04 UTC, rgbkrk commented on applications/desktop/__tests__/renderer/epics/github-publish-spec.js
>        false,
This should all make @jdetle happy! 🎉

2018-02-08 00:04 UTC, rgbkrk commented on packages/core/src/selectors/index.js
> +export const serverConfig = createSelector(
👍

2018-02-08 00:04 UTC, rgbkrk commented on packages/core/src/selectors/index.js
> +const identity = thing => thing;
heh

2018-02-08 00:04 UTC, rgbkrk commented on packages/core/src/selectors/index.js
> +import { toggleCellInputVisibility } from "../../actions";
How'd an action sneak in here?

2018-02-08 00:04 UTC, rgbkrk commented on packages/core/src/selectors/index.js
> +// notebook object to get. Do we return null? Throw an error?
I think `null` is fine

2018-02-08 00:04 UTC, rgbkrk commented on packages/core/src/selectors/index.js
> +);
Since we're having to put the selectors here for the github functionality, we might as well move the reducer from desktop's app reducer (and maybe the epic...). Not for this PR, but it'll be nice for desktop to have no custom reducers now.

2018-02-08 00:04 UTC, rgbkrk commented on packages/core/src/selectors/index.js
> +);
At some point we'll want to re-evaluate how we do run-all and run-all-below, since they belong in an epic that tracks the execution rolling on through.

2018-02-08 00:04 UTC, rgbkrk commented on packages/core/src/selectors/index.js
> +import { toggleCellInputVisibility } from "../../actions";
Looks like this didn't mean to be here

2018-02-08 00:04 UTC, rgbkrk commented on applications/desktop/src/notebook/epics/saving.js
> -
Ooooohhhh cool, we didn't need the notebook here anymore.

2018-02-08 00:16 UTC, rgbkrk commented
Separately, we should extract `getCodeMirrorMode` out as a selector too: https://github.com/nteract/nteract/blob/master/packages/core/src/providers/notebook-app.js#L295

2018-02-08 00:17 UTC, rgbkrk commented
We'll probably want to switch a lot of our `mapStateToProps` to using these as well.

2018-02-08 00:23 UTC, theengineear commented on packages/core/src/selectors/index.js
> +);
ah, didn't even realize that these were being set in desktop.

2018-02-08 00:24 UTC, rgbkrk commented on applications/desktop/src/notebook/global-events.js
>    );
This could be an `isSaved` selector.

2018-02-08 00:27 UTC, rgbkrk commented on packages/core/src/selectors/index.js
> +// notebook object to get. Do we return null? Throw an error?
That or `emptyNotebook` (from `commutable`)

2018-02-08 00:27 UTC, rgbkrk approved these changes

2018-02-08 00:28 UTC, merged