Halt Kernel in Menu
nteract/archived-desktop-app pull request #2529
Opened 2018-02-14 20:29 UTC by rgbkrk

As part of this, I created parametrized error actions for the boilerplatey `*failed` actions. It works well with flow too:

```js
let x: ?KillKernelFailed;

// Flow will bomb out here, as it expects the literal "KILL_KERNEL_FAILED"
x = {
  type: KILL_KERNEL,
  payload: new Error("test"),
  error: true
};

// ok with flow, like we want 👌🏻
x = {
  type: KILL_KERNEL_FAILED,
  payload: new Error("test"),
  error: true
};
```

* [x] create killKernel(success,fail)
* [x] create web based epic for killing kernel
* [x] put halt in the menu

2018-02-14 20:30 UTC, theengineear commented on packages/core/src/actionTypes.js
> +
✨

2018-02-14 20:30 UTC, theengineear commented on packages/core/src/actionTypes.js
> +export type InterruptKernelFailed = ErrorAction<"INTERRUPT_KERNEL_FAILED">;
💯

2018-02-14 20:32 UTC, theengineear commented on packages/core/src/epics/websocket-kernel.js
> +import * as actionTypes from "../actionTypes";
👌

2018-02-14 20:36 UTC, theengineear commented on packages/core/src/epics/websocket-kernel.js
> +}
IMO, this feels a little too clever. Just because you're passing the whole store into the function, if it was more than a one-liner, maybe, but I think the just seeing `filter(() => selectors.isCurrentHostJupyter(store.getState()))` is pretty clear. Anyways, just my opinion :)

2018-02-14 20:39 UTC, theengineear commented on packages/core/src/epics/websocket-kernel.js
> +    // kill, instead doing it after the last one happens
🥇

2018-02-14 20:44 UTC, theengineear commented on packages/core/src/epics/websocket-kernel.js
> +          catchError(err => actions.killKernelFailed(err))
🤔 this one always strikes me as funny. But... the thing that we're trying to return is the ajax response, which is why we have to flatten it. If that fails, we hit the `catchError`, which needs to match the nested structure of the failed ajax, right? I.e., don't we need like a `catchError(err => of(actions.killKernelFailed(err)))` here?

2018-02-14 20:44 UTC, theengineear commented on packages/core/src/epics/websocket-kernel.js
> +          catchError(err => actions.interruptKernelFailed(err))
Hmm. Now that I'm thinking about it, should this be wrapped as well?

2018-02-14 20:51 UTC, theengineear commented on packages/core/src/epics/websocket-kernel.js
> +          catchError(err => actions.killKernelFailed(err))
Ah, yah, this spec explains what's going on: https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/catchError.ts#L14

When one of the observables fails, you just switch to the one provided in the catchError instead. So yah, we definitely need this to be an observable.

2018-02-14 20:53 UTC, theengineear requested changes
Looks great! I think some of the `catchError` statements need to be updated though.

2018-02-14 21:00 UTC, rgbkrk commented on packages/core/src/epics/websocket-kernel.js
> +}
ok, I can move that back in

2018-02-14 21:03 UTC, rgbkrk commented on packages/core/src/epics/websocket-kernel.js
> +          catchError(err => actions.killKernelFailed(err))
ooooops

2018-02-14 21:04 UTC, rgbkrk commented on packages/core/src/epics/websocket-kernel.js
> +          catchError(err => actions.killKernelFailed(err))
Fixed it for both interrupt and kill just now!

2018-02-14 21:05 UTC, rgbkrk commented
It's too bad that flow doesn't recognize that the function passed to catchError must return an observable. I'm going to update the flow definition.

2018-02-14 21:06 UTC, rgbkrk commented
Hmmmm... Looks like `catchError` is `any` currently.

2018-02-14 21:10 UTC, rgbkrk commented
Welp, it looks like _all_ operators are currently untyped. 😭  Of course, I've already reported this (and made some PRs): https://github.com/flowtype/flow-typed/issues/1688

/cc @jayphelps

2018-02-15 03:24 UTC, theengineear commented on packages/core/src/epics/websocket-kernel.js
> +    filter(() => selectors.isCurrentHostJupyter(store.getState())),
Thanks!

2018-02-15 03:24 UTC, theengineear commented on packages/core/src/epics/websocket-kernel.js
> +          catchError(err => of(actions.killKernelFailed(err)))
🙇

2018-02-15 03:25 UTC, theengineear approved these changes

2018-02-15 03:25 UTC, merged