Introduce Typescript into the codebase,
nteract/archived-desktop-app pull request #3466
Opened 2018-10-19 15:37 UTC by jdfreder

and conver jupyter-widgets to typescript...
and ad some sanity tests.

2018-10-19 15:38 UTC, rgbkrk commented on tsconfig.json
> +    "paths": {
Wait, so `paths` is package names?

2018-10-19 16:14 UTC, jdetle commented
@jdfreder it looks like the tests are picking up javascript flowtypes as if they were typescript?

2018-10-19 16:21 UTC, jdetle commented on applications/jupyter-extension/nteract_on_jupyter/webpack.config.js
> +        test: /\.tsx?$/,
Why tsx versus ts?

2018-10-19 16:21 UTC, jdetle commented on packages/jupyter-widgets/tsconfig.json
> +    "outDir": "./dist/"
We usually build packages with lib over dist I think? Or is this doing something else?

2018-10-19 16:21 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/webpack.config.js
> +        test: /\.tsx?$/,
Hmmm yeah we want both here.

2018-10-19 18:27 UTC, jdetle commented on applications/jupyter-extension/nteract_on_jupyter/webpack.config.js
> +        test: /\.tsx?$/,
I think we don't want to use the ts-loader at all. We should be using the babel loader at all times.

2018-10-19 18:49 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/webpack.config.js
> +        test: /\.tsx?$/,
ah that's probably true since we're using babel 7

2018-10-19 18:49 UTC, rgbkrk commented on packages/jupyter-widgets/tsconfig.json
> +    "outDir": "./dist/"
yeah

2018-10-19 23:05 UTC, jdfreder commented
Weird, this passed `yarn test` locally.

2018-10-26 14:26 UTC, jdetle commented
@jdfreder, what do you want to do you with this?

2018-10-26 17:58 UTC, rgbkrk commented
John usually works on this stuff on nights and weekends so you might not see a response until tonight or tomorrow. 😄

2018-10-27 01:14 UTC, jdfreder commented
Kyle's right, my day job is mostly unrelated so I'm left to work on this on my time off, sorry. I plan to rebase this off of the PR you and I collaborated on. I probably won't get to it tonight, but I'll let you know as soon as I do.

2018-11-01 14:46 UTC, jdfreder commented on packages/jupyter-widgets/tsconfig.json
> +    "outDir": "./dist/"
fixed - thanks

2018-11-01 14:48 UTC, jdfreder commented
I just rebased this and I doubt it will pass because I haven't tested it locally, but I haven't forgotten about it. Just leaving a comment so that you don't close the PR. :)

2018-11-01 16:29 UTC, rgbkrk commented
Cool! One thing you may want to check out is the new doc for the typescript migration: https://github.com/nteract/nteract/blob/master/doc/design/typescript.md

2018-11-02 03:05 UTC, jdfreder commented
Nice doc!

2018-11-02 03:05 UTC, jdfreder commented on tsconfig.json
> +    "paths": {
The asterisk is, yes

2018-11-02 18:05 UTC, charlesjolley requested changes
Glad to see work on this! I posted a few comments.  I would especially like to avoid adding the paths property back to the tsconfig.base if possible.

2018-11-02 18:05 UTC, charlesjolley commented on packages/jupyter-widgets/package.json
>      "build:lib": "babel -d lib src --ignore '**/__tests__/**' --config-file ../../babel.config.js",
this script (and a few others I think) are wrong. Correct scripts are in the [TypeScript Doc](https://github.com/nteract/nteract/blob/master/doc/design/typescript.md)

2018-11-02 18:05 UTC, charlesjolley commented on packages/jupyter-widgets/src/index.tsx
> +  private container: { current: null | HTMLDivElement } = React.createRef();
I would omit the explicit type here, since assigning the createRef value will correctly set the type. createRef has a generic to set the element by the way:  `container = React.createRef<HTMLDivElement>();`

2018-11-02 18:05 UTC, charlesjolley commented on packages/jupyter-widgets/src/index.tsx
> +  render(): React.ReactElement<any> {
personal opinion, I would remove the type here altogether. I think this is unnecessarily expanding more strict typing you will get from React. I might be wrong though as I haven't tried it myself.

2018-11-02 18:05 UTC, charlesjolley commented on tsconfig.base.json
> +    "paths": {
Why did you add the `paths` property back? I took it out because it was causing some conflicts with normal package resolution. Ideally we can find a way to avoid using paths since yarn workspaces already makes local packages available

2018-11-03 16:18 UTC, jdfreder commented on packages/jupyter-widgets/package.json
>      "build:lib": "babel -d lib src --ignore '**/__tests__/**' --config-file ../../babel.config.js",
Thanks, yeah I saw the doc because Kyle shared it with me, it's very nice. I haven't had time to actually update this PR until now (I've just been rebasing it so that it doesn't fall too far behind). I'll ping back when it's ready for a review.

2018-11-03 18:53 UTC, jdfreder commented on packages/jupyter-widgets/package.json
>      "build:lib": "babel -d lib src --ignore '**/__tests__/**' --config-file ../../babel.config.js",
:heavy_check_mark:

2018-11-03 18:53 UTC, jdfreder commented on packages/jupyter-widgets/src/index.tsx
> +  private container: { current: null | HTMLDivElement } = React.createRef();
:heavy_check_mark:

2018-11-03 18:53 UTC, jdfreder commented on packages/jupyter-widgets/src/index.tsx
> +  render(): React.ReactElement<any> {
:heavy_check_mark: that makes sense

2018-11-03 18:53 UTC, jdfreder commented on tsconfig.base.json
> +    "paths": {
:heavy_check_mark:  - it was left over from earlier

2018-11-03 18:54 UTC, jdfreder commented
This is ready to be reviewed and/or merged - please take a look when you have a moment.

2018-11-04 15:30 UTC, charlesjolley approved these changes

2018-11-04 15:30 UTC, charlesjolley commented
LGTM!

2018-11-04 17:05 UTC, merged