Jsral/add missing dependencies
nteract/archived-desktop-app pull request #3473
Opened 2018-10-21 03:29 UTC by jamessral

Add missing dependencies to packages

* Attempts to address issue #3471 by adding `import/no-extraneous-dependencies` rule
  and adding appropriate packages to package.json file

- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

2018-10-21 04:00 UTC, jamessral commented
For some reason, I'm having difficulty with the `jupyter-extension` errors and the `records` errors. For the former, I've tried installing the packages (`npm i -S immutable` and `npm --save-dev lodash-webpack-plugin`), but I still seem to get the errors. For the latter, I'm not sure really what to do about that error since it seems to be referencing itself as a package.

2018-10-21 11:58 UTC, lgeiger requested changes
Thanks a lot for tackling this issue 🎉 

As mentioned in the relevant issue, a convention we currently follow is to require `react`, `react-dom` and `immutable` as `peerDependencies` rather than `dependencies`. There are a few places where you added them as direct dependencies. You probably followed the prompt to install them via `npm` rather than copying from another `package.json`, I should've clarified this in the issue.

2018-10-21 11:58 UTC, lgeiger commented on applications/commuter/package.json
> +    "immutable": "^3.8.2",
This looks like you just installed it with `npm` rather than copying it to from another `package.json`. We're requiring version `"immutable": "^4.0.0-rc.9"` instead of version 3. This needs to be changed in a few other places too.

2018-10-21 11:58 UTC, lgeiger commented on applications/desktop/package.json
> +    "yargs": "^12.0.2"
These should all be dev dependencies since we're using webpack to bundle the app. Otherwise they would be included in the electron bundle two times. We're only requiring the ones we explicitly exclude from the webpack bundle as dependencies.

2018-10-21 11:58 UTC, lgeiger commented on packages/connected-components/package-lock.json
> +{
We're using `yarn` to install our dependencies. Thus there should be no `package-lock.json` files in the repo.

2018-10-21 11:58 UTC, lgeiger commented on packages/core/package.json
> +    "lodash": "^4.17.11",
Nice

2018-10-21 11:58 UTC, lgeiger commented on packages/markdown/package.json
> +    "unist-builder": "^1.0.3"
Oh wow so many missing dependencies 👀

2018-10-21 11:58 UTC, lgeiger commented on packages/notebook-render/package.json
> +    "react-dom": "^16.3.2",
This should be a `devDependency` since it's required in `__test__` only.

2018-10-21 11:58 UTC, lgeiger commented on packages/outputs/package-lock.json
> +{
We're using `yarn` to install our dependencies. Thus there should be no `package-lock.json` files in the repo.

2018-10-21 11:58 UTC, lgeiger commented on packages/records/package.json
> +    "uuid": "^3.3.2"
We require `^3.1.0` every where else in the repo. It's better to keep the in sync.

2018-10-21 11:58 UTC, lgeiger commented on packages/styled-blueprintjsx/package-lock.json
> +{
We're using `yarn` to install our dependencies. Thus there should be no `package-lock.json` files in the repo.

2018-10-21 11:58 UTC, lgeiger commented on packages/styleguide-components/package-lock.json
> +{
We're using `yarn` to install our dependencies. Thus there should be no `package-lock.json` files in the repo.

2018-10-21 12:02 UTC, lgeiger commented
> For some reason, I'm having difficulty with the jupyter-extension errors and the records errors. For the former, I've tried installing the packages (npm i -S immutable and npm --save-dev lodash-webpack-plugin), but I still seem to get the errors

Probably the easiest thing would be to just add the dependency to the `package.json` manually. I'm not surprised that installing via `npm` this doesn't work since we're using [`yarn`](https://yarnpkg.com) to manage our dependencies. Sorry, I should've mentioned this earlier.

> For the latter, I'm not sure really what to do about that error since it seems to be referencing itself as a package.

`@nteract/records` requires itself inside the tests. The best thing here would probably to switch it to relative imports as we do in the other tests.

2018-10-21 14:19 UTC, rgbkrk commented
Within our `yarn` workspace setup the easiest way to add deps is using [`yarn workspace @nteract/packageName add somePackage`](https://yarnpkg.com/en/docs/cli/workspace).

This functions the same as `yarn add` with workspaces in mind so you can include flags like `--peer` and `--dev`.

2018-10-22 15:42 UTC, lgeiger commented
This makes me think if we should start moving all the dev dependencies to their respective packages 🤔 

Installing everything to the root `packages.json` has caused some confusion in recent PRs and we would now have a ESLINT rule to enforce  the correct dev dependencies in our packages.

@rgbkrk What do you think?

2018-10-22 18:20 UTC, rgbkrk commented
There has certainly been ask for us to have `devDependency` on the packages so that people can hack on them when they're trying to work on a separate code base. I think the `yarn` workspace stuff is more efficient with this now, we're no longer having to worry about `lerna` install a package N times then reduce it to 1.

2018-10-24 13:15 UTC, jamessral commented
Do you have a preferred way for me to do it, then? I can do it either way

2018-10-24 15:38 UTC, rgbkrk commented
Seems like the verdict is -- include the right `devDependency` for each package. It would be ok if you started new PRs that did it package by package. Right now there are quite a few conflicts that may not be fun to work though. 

You'll want to use:

```
yarn workspace @nteract/packageName add somePackage --dev
```

2018-12-26 14:27 UTC, closed without merging

2018-12-26 20:05 UTC, rgbkrk commented
Hey thanks for giving this a try, sorry these didn't make it through in due time.

2018-12-26 20:22 UTC, jamessral commented
No worries. Everyone gets busy :smile: Perhaps I'll have time to try again some time. I only closed these because they should probably be done again with more recent versions