Enforce react/jsx-no-bind rule
nteract/archived-desktop-app pull request #3474
Opened 2018-10-21 06:11 UTC by showmeyourhits

- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

2018-10-21 12:30 UTC, lgeiger requested changes
@showmeyourhits Thanks a lot for the great work 🎉 . This is quite a huge PR now.

We're using [flow](https://flow.org/) to typecheck our code. Unfortunately your changes introduced [some type errors](https://circleci.com/gh/nteract/nteract/3255?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), it would be wonderful if you could fix them. You can typecheck the code by running `yarn flow` which also integrates well with a lot of text editors or IDEs.

If you need help, please join our slack at http://slack.nteract.io. I'm also happy to pair up with you on video to tackle those errors.

2018-10-21 12:30 UTC, lgeiger commented on applications/commuter/components/contents/html.js
> +  setIframeRef = f => {
Any reason why not using the [`React.createRef` API](https://reactjs.org/docs/react-api.html#reactcreateref)?

2018-10-21 12:30 UTC, lgeiger commented on packages/transforms/src/html.js
> +  elRef: React.Ref<HTMLElement>;
I guess this should be `elRef: React.ElementRef<*>;` to appease flow.

2018-10-21 12:30 UTC, lgeiger commented on packages/transforms/src/html.js
> +
I think this can benefit from some cleanup. Instead of using a constructor:
```js
export default class HTMLDisplay extends React.Component<Props> {
  elRef: elRef: React.ElementRef<*>;
  constructor(props: Props) {
    super(props);
    this.elRef = React.createRef();
  }
}
 ```
This can be simplified to:
```js
export default class HTMLDisplay extends React.Component<Props> {
  elRef: React.ElementRef<*> = React.createRef();
}
 ```

2018-10-28 12:17 UTC, lgeiger approved these changes
@showmeyourhits Thanks a lot for this work. This is getting quite a huge PR now 👀

Looks like there's only one file left: https://circleci.com/gh/nteract/nteract/3408?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@emeeks This touches quite a bit of code from the data explorer. Could you take a quick look?

2019-01-03 17:58 UTC, rgbkrk commented
Closing as we're using tslint and adhering to the rules along with our typescript config.

2019-01-03 17:58 UTC, closed without merging