[WIP] Create @nteract/epics package
nteract/archived-desktop-app pull request #3681
Opened 2018-11-21 01:43 UTC by captainsafia

2018-11-28 17:01 UTC, rgbkrk commented
Coordinating with Safia now, I'm going to continue on with this PR. I'll be force pushing since there are conflicting files to resolve with a rebase.

2018-11-28 17:05 UTC, rgbkrk commented on package.json
>      "@types/immutable": "^3.8.7",
It just dawned on me these types are likely wrong. We're on immutable 4.0.0-rc.12

2018-11-28 17:06 UTC, rgbkrk commented on package.json
>      "@types/immutable": "^3.8.7",
Ah we can delete it: https://www.npmjs.com/package/@types/immutable

> This is a stub types definition for Facebook's Immutable (https://github.com/facebook/immutable-js). Facebook's Immutable provides its own type definitions, so you don't need @types/immutable installed!

2018-12-06 00:16 UTC, captainsafia commented
It's ready for review!

![image](https://user-images.githubusercontent.com/1857993/49552591-e3d7a980-f8b9-11e8-83bc-c2331f5542ec.png)

2018-12-06 06:33 UTC, rgbkrk requested changes
Excellent work getting this migrated!

Since I think this is really close, I wouldn't let my comments about moving some of the changes to a new PR hold this back. Focus on the other ones like removing that invalid `@types/immutable` include.

2018-12-06 06:33 UTC, rgbkrk commented on package.json
>      "@types/immutable": "^3.8.7",
This'll still need to be deleted.

2018-12-06 06:33 UTC, rgbkrk commented on packages/actions/src/actions.ts
> +  contentRef?: ContentRef;
If this ends up getting to be a messy PR for review, you might want to move this to a new commit on a new branch + PR.

2018-12-06 06:33 UTC, rgbkrk commented on packages/epics/README.md
> +// TODO: DEMONSTRATE API
Likely example to pull from is how desktop stitches together epics.

2018-12-06 06:33 UTC, rgbkrk commented on packages/epics/__tests__/epics.test.js
> +    expect(true).toEqual(true);
I'm assuming you'll bring over the tests for the current epics (assuming we have those...)

2018-12-06 06:33 UTC, rgbkrk commented on packages/epics/package.json
> +  "description": "Epics for interfacing with the Jupyter ecosystem",
"Redux-Observable epics for nteract apps"

2018-12-06 06:33 UTC, rgbkrk commented on packages/epics/src/comm.ts
> +  ); // We have a new channel
This comment belongs above the `ofType` operator since it's describing that we launched a new kernel and are `switchMap`ing to kill off old comm listeners.

2018-12-06 06:33 UTC, rgbkrk commented on packages/epics/src/contents.ts
> +  state$: StateObservable<AppState>
We may want to make `AppState` a bit loose (maybe this already handles it) so that this epic only has to recieve our base state. Mostly so that any apps that with additional properties can still use this typed epic.

2018-12-06 06:33 UTC, rgbkrk commented on packages/epics/src/contents.ts
> +    // we should use the state$ stream to only save when the content has changed
We're now on redux observable 1.0.0 so we can use the `state$` stream. Probably good to update this TODO and possibly leave it as a note instead.

2018-12-06 06:33 UTC, rgbkrk commented on packages/messaging/src/messages.ts
> + *
This is all definitely highlighting that something is consistent about our prettier eslint setup. Not sure what's going on.

2018-12-06 06:33 UTC, rgbkrk commented on packages/messaging/src/messages.ts
> +    buffers: new Uint8Array()
Could probably move this out to another PR, as well as any other `messaging` changes, then do an interactive rebase.

2018-12-06 15:25 UTC, captainsafia commented on packages/epics/__tests__/epics.test.js
> +    expect(true).toEqual(true);
Yes, we do! Bringing them in now.

2018-12-06 15:26 UTC, captainsafia commented on packages/epics/package.json
> +  "description": "Epics for interfacing with the Jupyter ecosystem",
Done.

2018-12-06 15:41 UTC, captainsafia commented on packages/epics/src/contents.ts
> +  state$: StateObservable<AppState>
Hm. I guess we can change this type definition to `Partial<AppState>` then. This way, it will accommodate objects that are missing some of the AppState fields and those that have extra fields.

2018-12-07 17:58 UTC, captainsafia commented on packages/messaging/src/messages.ts
> + *
I recently enabled format on save in my VSCode so I think it caught something that hadn't been formatted before.

2018-12-07 18:02 UTC, rgbkrk approved these changes
This is looking great, thanks for persevering through this one!

2018-12-07 18:02 UTC, captainsafia commented on packages/messaging/src/messages.ts
> +    buffers: new Uint8Array()
I think it makes more sense to keep it here. The problem stemmed from the fact that our actions definitions had the `Uint8Array` type defined for all buffers. However, our custom type declarations for JMP used `any[]` as the type for buffers. Since `messaging` was converted before the actions and epics, it was set up to match up with the loosely-typed declarations we had. This makes sure that messages and JMP type declarations are using the stricter definitions everywhere.

2018-12-07 18:02 UTC, merged