[WIP] Persist metadata after UI controls changes in DX
nteract/archived-desktop-app pull request #3841
Opened 2018-12-12 20:13 UTC by emeeks

* Actions

2018-12-13 20:09 UTC, emeeks commented
CI is failing but the functionality is working, would love comments and review

![itt_muse_3](https://user-images.githubusercontent.com/495634/49964650-dfba1600-fecf-11e8-97f4-4b3fe1393196.gif)

2018-12-13 23:33 UTC, rgbkrk commented on packages/display-area/src/richest-mime.tsx
> +          ...scopedChanges
Passing mimetype as one of the arguments is making this more complex than necessary. I'd go for bubbling up the metadata like this:

```js
this.props.onMetadataChange({
  ...this.props.metadata,
  [mimetype]: scopedChanges
})
```

so you don't have to bubble the mimetype up and re-work it above.

2018-12-13 23:33 UTC, rgbkrk commented on packages/notebook-app-component/src/notebook-app.tsx
> +  const metadata = (cell.getIn(["metadata"]) || Immutable.Set()).toJS();
This should be an `Immutable.Map`.

2018-12-13 23:35 UTC, rgbkrk commented on packages/reducers/src/core/entities/contents/notebook.ts
> +  );
This looks like it's setting the metadata on the cell rather than the output, where the metadata belongs.

2018-12-14 00:19 UTC, emeeks commented on packages/reducers/src/core/entities/contents/notebook.ts
> +  );
The reason I was passing mimeType through was because I didn't think to pass the metadata through to the output and mimetype lets me do that cleaner `setIn`. How would I set the metadata of the output?

2018-12-14 00:21 UTC, emeeks commented on packages/display-area/src/richest-mime.tsx
> +          ...scopedChanges
This is the right way to go once I figure out how to send it to the output rather than the metadata of the cell.

2018-12-14 17:53 UTC, rgbkrk approved these changes

2018-12-14 17:53 UTC, rgbkrk commented on packages/actions/src/actionTypes/cells.ts
> +export const UPDATE_CELL_METADATA = "UPDATE_CELL_METADATA";
Should switch this over to `UPDATE_OUTPUT_METADATA`

2018-12-14 17:53 UTC, rgbkrk commented on packages/display-area/src/output.tsx
> +  onMetadataChange?: Function;
Instead of typing this as `Function`, you can make this explicit with a type `(metadata: Object) => void`.

2018-12-14 17:53 UTC, rgbkrk commented on packages/reducers/src/core/entities/contents/notebook.ts
> +      (item: any) => item.get("output_type") === "execute_result"
There can be more than one `execute_result` in a collection of outputs and the data explorer can also exist on output type `display_data`. Since we don't have IDs for outputs, you'll have to pass the index of the output that got the on metadata change callback.

2018-12-14 17:54 UTC, rgbkrk requested changes
Whoops, meant to mark this as needing changes, not approved. 😄

2018-12-14 18:44 UTC, emeeks commented on packages/actions/src/actionTypes/cells.ts
> +export const UPDATE_CELL_METADATA = "UPDATE_CELL_METADATA";
Weird, not sure how I missed this one.

2018-12-15 20:10 UTC, rgbkrk commented on packages/actions/src/index.ts
> +import * as ActionTypes from "./actionTypes/index";
Was this import necessary?

2018-12-15 22:44 UTC, emeeks commented on packages/actions/src/index.ts
> +import * as ActionTypes from "./actionTypes/index";
Nope! Just left from some logging an issue and accidentally left it in.

2018-12-16 15:30 UTC, captainsafia reviewed
Looks great! I left some comments related to the types inline.

2018-12-16 15:30 UTC, captainsafia commented on packages/actions/src/actionTypes/cells.ts
> +    metadata: Object;
You'll probably want to replace this with `JSONObject`. In TypeScript, `Object` represents all JavaScript objects, not objects like {}.

2018-12-16 15:30 UTC, captainsafia commented on packages/actions/src/actions/cells.ts
> +  metadata: Object;
Ditto here as well.

2018-12-16 15:30 UTC, captainsafia commented on packages/display-area/src/display.tsx
> +                <Output key={index} index={index} output={output} {...props} />
What is this new `index` prop being used for?

2018-12-16 16:23 UTC, emeeks commented on packages/actions/src/actionTypes/cells.ts
> +    metadata: Object;
Didn't realize, thanks!

2018-12-16 16:26 UTC, emeeks commented on packages/display-area/src/display.tsx
> +                <Output key={index} index={index} output={output} {...props} />
It's used to know in the updateOutputMetadata in `output.tsx` function which output in the arrays of outputs to update.

2018-12-17 20:43 UTC, merged

2018-12-17 22:23 UTC, rgbkrk commented
Thank you!