Fixes Kernel Keybindings
nteract/archived-desktop-app pull request #4209
Opened 2019-02-13 19:10 UTC by stormpython

Currently, the keybindings for kernel actions does not work. This PR address this bug by passing a `faked` kernelRef to the kernel `actions`.

2019-02-13 19:13 UTC, stormpython commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx
> +  const kernelRef = createKernelRef();
Is this ok to do? I am not sure. The other option: I can require a `kernelRef` be passed to the `<Notebook />` component.

2019-02-13 19:18 UTC, stormpython commented
This PR also moves the `HotKey` functionality from the `.../contents/index.tsx` file to the `.../contents/notebook.tsx` file. This is moved because hotkeys are really only valid for the notebooks and not files or directories.

2019-02-13 19:31 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx
> +  const kernelRef = createKernelRef();
Wait, so is the kernelRef here even used? I'm assuming it's looked up via the `contentRef` instead?

2019-02-13 20:21 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx
> +    // because of the basemap URL(s)
This TODO can be removed so that the TODO bot doesn't add this (again). @captainsafia handled this for the GeoJSON transform IIRC.

2019-02-13 20:31 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx
> +  const kernelRef = createKernelRef();
The way I'd do this is:

```ts
const makeMapDispatchToProps = (dispatch: Dispatch, ownProps: NotebookProps) => {
  const { contentRef } = ownProps;
  return function mapDispatchToProps(state: AppState) {
    const content = selectors.content(state, { contentRef });

    if (!content || content.type !== "notebook") {
      return { 
        // likely just return some unbound segment of these?
      };
    }

    const kernelRef = content.model.kernelRef; // this is the active kernelRef

    return {
      addTransform: ...,
      INTERRUPT_KERNEL: () => dispatch(actions.interruptKernel({ kernelRef })),
      // ...the rest of them
  }

}
```

2019-02-13 20:34 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx
> +  const kernelRef = createKernelRef();
Alternatively, we can set the `kernelRef` in the `props` via `mapStateToProps` then pass them to the respective handlers (?).

This leads me to believe we probably shouldn't use state in `mapDispatch` though -- https://github.com/reduxjs/react-redux/issues/535#issuecomment-257692617

2019-02-14 18:07 UTC, stormpython commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx
> +  const kernelRef = createKernelRef();
The inner `mapDispatchToProps` function doesn't get `state` passed to it. It is the `dispatch` and `ownProps` that are passed.

2019-02-14 18:36 UTC, stormpython commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx
> +  const kernelRef = createKernelRef();
It seems that `state` isn't passed into `mapDispatchToProps` at all. And, since I was setting the `kernelRef` as a prop from `mapStateToProps`, the initial value is undefined. And even after its updated, the `mapDispatchToProps` function still holds onto the initial value because the `dispatch` functions are not reattached unless `ownProps`, i.e. values passed into the component, changes. So, the `kernelRef` is never updated.

2019-02-15 16:10 UTC, rgbkrk commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx
> +  const kernelRef = createKernelRef();
Whoop!

Yeah we'd have to weave in `kernelRef` via `mapStateToProps` via the state, then pass the `kenrelRef` into the functions for `dispatch`.

2019-03-01 21:27 UTC, rgbkrk requested changes
We'll still need to handle the `kernelRef` here: https://github.com/nteract/nteract/pull/4209/files#r257295699

2019-04-12 18:34 UTC, stormpython commented
Ok, I've added the logic for `kernelRef` to be passed down to the `File` component in order to have the keybindings work properly. However, there are two concerns that I have about the current implementation of keybindings.

1. Pressing `Hotkeys` are not being registered by the UI, possibly because of where the blueprintjs `Hotkeys` component is placed.
2. The Notebook Menu uses the `currentKernelRef` prop but the `kernelRef` which is passed down from the `App` component is used by the `File` component. I am not sure if these two things are the same. My guess is that the `currentKernelRef` is computed because the `NotebookMenu` is a connected component and is pulling the `currentKernelRef` from state in the `mapStateToProps`.

2019-04-13 02:53 UTC, captainsafia commented on applications/jupyter-extension/nteract_on_jupyter/app/bootstrap.tsx
> +        <App contentRef={contentRef} kernelRef={kernelRef} />
I would use `mapStateToProps` to get the kernelRef. This passes the first generated kernelRef to the app, if the user restarts the kernel using the menu this prop won't be updated correctly.

2019-04-13 02:53 UTC, captainsafia commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/headers.tsx
> +  static defaultProps: { children: any } = {
`children` can be typed as `React.ReactNode` here.

2019-05-06 21:37 UTC, stormpython commented on applications/jupyter-extension/nteract_on_jupyter/app/bootstrap.tsx
> +        <App contentRef={contentRef} kernelRef={kernelRef} />
Can we talk about this because I don't have a good understanding of how the `kernelRef` life cycle works. For example, when I refresh the browser, I get a new kernelRef that doesn't match the previous kernelRef. And when I was using the kernelRef from `mapStateToProps` it was complaining that the kernelRef I was using to interrupt or shutdown was not valid.

2019-05-07 17:10 UTC, stormpython commented on applications/jupyter-extension/nteract_on_jupyter/app/contents/headers.tsx
> +  static defaultProps: { children: any } = {
I will change this.

2019-05-10 14:27 UTC, willingc commented
@stormpython Is this good to merge?

2019-05-10 16:59 UTC, willingc commented
Oops needs a rebase.

2019-12-23 18:49 UTC, rgbkrk commented
Since this is way out of sync with the current `master` and I know Shelby is working on other things at the moment, I'm going to go ahead and close. Thanks Shelby!

2019-12-23 18:49 UTC, closed without merging