Fix execute and shift focus flow on Markdown cells
nteract/archived-desktop-app pull request #4528
Opened 2019-08-26 02:38 UTC by captainsafia

Closes #4524 

Ctrl + Enter now shifts to focus on the editor only if the following cell is a code cell or a cell added at the end of the notebook. Ctrl + Enter will still focus on Markdown cells but not enter edit mode.

2019-08-26 06:24 UTC, motin requested changes
I tested the changes in the desktop app and indeed the new behavior is much more pleasant and matches the discussion in #4524 

I'd love to see a second test added under the `"detects a focus to next cell keypress"` test which presses shift+enter again and does not `expect(focusNextCellEditor).toHaveBeenCalled();`.

That and to resolve the linting errors :)

2019-08-26 06:24 UTC, motin commented on packages/notebook-app-component/src/notebook-app.tsx
> +        focusNextCellEditor({ id: focusedCell, contentRef });
Out of curiosity, what does sending `focusedCell` do here rather than sending `undefined`?

2019-08-26 18:26 UTC, captainsafia commented on packages/notebook-app-component/src/notebook-app.tsx
> +        focusNextCellEditor({ id: focusedCell, contentRef });
Previously, if the `id` passed here was `undefined` it would use the value of the currently focused editor. It would then advance the focus to the editor following it.

However, there can be a situation where a user has CodeA, MDA, CodeB. The cell focus might be on MDA but the editor focus might be on CodeA. With the pre-existing behavior, Ctrl + Enter on MDA would have shifted the cell focus to CodeB and the editor focus to MDA.

Instead, we want the editor focus to always be the focused cell if it is a code cell.

Note that I added a `|| undefined` in my latest PR to resolve some type issues. Practically, the `focusedCell` should never be null but ImmutableJS's type definitions for `gets` constrain us here.

2019-08-26 18:27 UTC, captainsafia commented
@motin Thanks for the feedback, Frederik! I've added tests and fixed the lint errors.

2019-08-27 09:47 UTC, motin approved these changes
Looks super! Thanks @captainsafia :)

2019-08-27 15:55 UTC, merged