Upgrade react-syntax-highlighter in presentational-components (again, with less problems, hopefully)
nteract/archived-desktop-app pull request #4669
Opened 2019-11-02 10:57 UTC by akx

Ugh, sorry about the mess I brought on in #4636 (refs #4663, #4664).
I was actually bit by it personally too, now that the upgraded module was published. 😅 

This is essentially the same PR as #4636, but without ESM imports; I just vendored in those troublesome theme modules instead.

2019-11-02 20:02 UTC, wadethestealth commented
Before merging, I need to test that this would work in Hydrogen. I will update this comment with the results.

2019-11-03 00:29 UTC, rgbkrk commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
One way of guaranteeing this working is by using the [direct cjs import the library authors recommend (though stated as non-ideal)](https://github.com/conorhastings/react-syntax-highlighter/blob/d58813a0f2e2fd4ba94e5c1122e1ddb9ca01f67f/CHANGELOG.MD#changed-1):

```
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter/dist/cjs/prism";
```

2019-11-03 01:35 UTC, wadethestealth requested changes

2019-11-03 01:35 UTC, wadethestealth commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
Currently, this dosn't even build to test builds please run `tsc -b packages/presentational-components` to test bulding
```
packages/presentational-components/src/syntax-highlighter/index.tsx:2:9 - error TS2305: Module '"react-syntax-highlighter"' has no exported member 'Prism'.

2 import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
```

2019-11-04 13:00 UTC, akx commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
Wait, um, I'm not seeing that (and CI passes too)...

```shell
$ git rev-parse HEAD
b5ed3382ab2ea9085d203a1e6c85d2e82ba67150
$ ./node_modules/.bin/tsc -b packages/presentational-components
$
```

2019-11-04 13:01 UTC, wadethestealth commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
The ci passes because this module has no tests

2019-11-04 13:02 UTC, wadethestealth commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
I think that was my mistake though let me try again.

2019-11-04 13:05 UTC, akx commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
`react-syntax-highlighter`'s `package.json` has 
```json
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index.js",
```
so bundlers/runtimes will know to use the ESM build if they're ESM aware, and use the CJS build otherwise.

The problem was with the direct imports of `esm` style theme modules which didn't get transpiled and thus were not importable.

As for the theme modules, sure, they could be imported `cjs` style, so they wouldn't need to get bundled, at the likely expense of a little more boilerplate in the code here. I can do that, too, if that's preferred over vendoring the themes.

2019-11-04 13:17 UTC, wadethestealth commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
Ok that was totally my fault. It does build, but we do need to be careful because the ci does not test this module

2019-11-04 13:18 UTC, wadethestealth commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
I think importing a cjs rather then updating a vender everytime they do is much more preferred

2019-11-06 10:54 UTC, akx commented on packages/presentational-components/src/syntax-highlighter/index.tsx
> +import {Prism as SyntaxHighlighter} from "react-syntax-highlighter";
Okiedoke, changed that. Did mean I had to add an "ad-hoc" `.d.ts` file for the two modules, but it's explained in the commit message.

2019-11-06 22:02 UTC, wadethestealth approved these changes

2019-11-06 22:02 UTC, merged

2019-11-07 06:58 UTC, akx commented
Thanks! Here's hoping I don't break anything this time...