Updates cell styles
nteract/archived-desktop-app pull request #5151
Opened 2020-06-09 16:24 UTC by ryanlanciaux

This PR updates the Cell styles. In this paradigm, the Cell actions are no longer in a floating toolbar and are now in a popout menu. 

![cell](https://user-images.githubusercontent.com/85041/84173825-cd308680-aa4b-11ea-84ca-2a826a5630a3.gif)

## TODO
There are a couple of things that need to occur before moving this from a Draft to a final PR.

- [ ] Update tests
- [ ] Run the application in more scenarios
- [ ] Ensure that the Toolbar does not expand outside the visible area when on the last Cell.

- [x] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)
- [ ] I have updated the changelogs/current_changelog.md file with some information about the change that I am making the appropriate file.
- [ ] I have validated or unit-tested the changes that I have made.
- [ ] I have run through the TEST_PLAN.md to ensure that my change does not break anything else.

2020-06-10 02:53 UTC, captainsafia commented
Gave this a spin. Exciting to see the new changes.

One piece of feedback I have is the interaction with the input is hidden.

Currently, it just hides the text. Typically, users will want to entire input area to be hidden and the toolbar elements to be moved adjacent to the output.

Also, I feel like there should be a bit of a margin in the output so that it lines up with the cell toolbar.

2020-06-11 15:06 UTC, ryanlanciaux commented
@captainsafia Thanks a ton for this feedback! Do you think it would make sense if I switched the layout to where the toolbar elements is on the left of both the input and the output? I think that may cover both the margin and condensing things a bit when the input is hidden. 

Thanks!

2020-06-13 02:23 UTC, captainsafia commented
>  Do you think it would make sense if I switched the layout to where the toolbar elements is on the left of both the input and the output?

I think I am visualizing the same thing you are with this description and it sounds like a sensible approach.

2020-06-15 11:50 UTC, ryanlanciaux commented
Okay great! I've updated this PR with the styling updates so the sidebar stays next to the output when the input is hidden:

![image](https://user-images.githubusercontent.com/85041/84654161-b0c59b80-aedc-11ea-935f-0d105ea2bbd1.png)

Additionally, I've updated the color of the sidebar. I'm still seeing some failing tests, and I'm trying to determine how this may have broken them.

2020-06-17 05:21 UTC, captainsafia requested changes
Looks good overall! This is really close to being mergeable.

One issue I noticed is with markdown cells. The markdown previewer applies its own gutter styling which results in an extra gray area inside the input text.

<img width="775" alt="Screen Shot 2020-06-16 at 9 57 00 PM" src="https://user-images.githubusercontent.com/1857993/84858268-ae1f8f00-b01f-11ea-98d5-5d79bce2acf9.png">

2020-06-17 05:21 UTC, captainsafia commented on packages/presentational-components/package.json
> +    "@types/classnames": "^2.2.10",
Let's move this to `devDependencies`.

2020-06-17 05:21 UTC, captainsafia commented on packages/presentational-components/package.json
> +    "react-toggle": "^4.1.1"
This should be under `dependencies` I believe.

2020-06-17 05:21 UTC, captainsafia commented on packages/notebook-app-component/src/derived-components/toolbar.tsx
> -              <DropdownMenu
We might want to set some tabindexes on the menu items.

I can tab from the `Play` button to the `Toolbar` icon and press enter to show the toolbar. From that point on, I cannot tab through the menu options in the toolbar.

2020-06-17 05:21 UTC, captainsafia commented on packages/stateful-components/src/cells/toolbar.tsx
> -      <div className="nteract-cell-toolbar">
The `nteract-cell-toolbar` classname is part of the public API that we provide as part of stateful components so we will need to keep it around.

Was there a particular reason it was removed?

2020-06-17 05:21 UTC, captainsafia commented on packages/styles/themes/default.css
> +.nteract-cell{
```suggestion
.nteract-cell {

```

2020-06-17 05:21 UTC, captainsafia commented on packages/styles/themes/default.css
> +.nteract-cell-row{
```suggestion
.nteract-cell-row {

```

2020-06-17 05:21 UTC, captainsafia commented on packages/styles/themes/default.css
> +.nteract-cell-container:focus .nteract-cell, .nteract-cell-container:focus-within .nteract-cell, .nteract-cell-container.selected .nteract-cell{
```suggestion
.nteract-cell-container:focus .nteract-cell,
.nteract-cell-container:focus-within .nteract-cell,
.nteract-cell-container.selected .nteract-cell {
```

2020-06-17 05:21 UTC, captainsafia commented on packages/styles/themes/default.css
>    color: var(--theme-app-fg);
Nit: Can you keep this file unchanged and move the styles related to a new theme to a new file?

2020-06-22 13:03 UTC, ryanlanciaux commented on packages/notebook-app-component/src/derived-components/toolbar.tsx
> -              <DropdownMenu
I think this should be working now.

2020-06-22 13:04 UTC, ryanlanciaux commented on packages/stateful-components/src/cells/toolbar.tsx
> -      <div className="nteract-cell-toolbar">
Sorry about that - there was no real reason. I've added it back in.

2020-06-22 13:05 UTC, ryanlanciaux commented on packages/styles/themes/default.css
>    color: var(--theme-app-fg);
That would definitely make things a bit cleaner. I've created a CSS file just to contain these styles.

2020-06-24 08:35 UTC, captainsafia approved these changes
Looks good overall. One last detail I noticed is the color of the toolbar and elements is a little off in dark mode.

This wasn't included in the original design so we might have to be creative with how it ends up looking here.

<img width="781" alt="Screen Shot 2020-06-24 at 1 34 31 AM" src="https://user-images.githubusercontent.com/1857993/85522826-0116ba80-b5bb-11ea-8fd2-1c5b2faabd63.png">

2020-06-24 18:49 UTC, captainsafia commented
Merging this now so that we can tackle to follow-ons in smaller PRs.

2020-06-24 18:49 UTC, merged