[WIP] New layout for @nteract/web
nteract/archived-desktop-app pull request #5167
Opened 2020-06-19 02:01 UTC by ramantehlan

![gscreenshot_2020-06-19-072842](https://user-images.githubusercontent.com/29037312/85088819-9c481280-b1fe-11ea-96a2-507d09bc5a49.png)

This PR is to introduce new components to [nteract/web](https://github.com/nteract/nteract/tree/master/applications/web) and make the application functional. The new components are developed in the [UI-web](github.com/nteract/ui-web/) repository and are gradually integrated here.

The list of components that needs to be created and added is given below, more might be added later:

- [x] Layout
- [x] BinderMenu
- [x] Input
- [x] Menu
- [x] Button 
- [x] Avatar
- [ ] Dialog
- [ ] Editor
- [ ] FileExplorer `will be adopted from UI-refresh`
- [ ] Notification `will be taken from nteract legacy lib`

2020-06-20 19:52 UTC, captainsafia reviewed
Looks good overall.

Main piece of feedback is to use the Monaco editor to render file contents and to ensure that we don't lose notebook rendering.

I haven't been able to get GitHub OAuth to work.

2020-06-20 19:52 UTC, captainsafia commented on applications/web/pages/p/[...params].tsx
> +import Editor from 'react-simple-code-editor';
We can use @nteract/monaco-editor here so we don't introduce another dependency. See the examples in the Jupyter extension for example.

2020-06-20 19:52 UTC, captainsafia commented on applications/web/pages/p/[...params].tsx
> +              <Editor
This renders everything inside an editor, including notebooks.

2020-06-20 19:52 UTC, captainsafia commented on applications/web/pages/util.js
> +function getFilePath(params){
This file shouldn't be under the pages directory.

Also, we generally try and stay away from `utils` folders. It seems like these functions should be implemented as anonymous functions in the main page.

2020-06-21 05:39 UTC, ramantehlan commented
> Looks good overall.
> 
> Main piece of feedback is to use the Monaco editor to render file contents and to ensure that we don't lose notebook rendering.
> 
> I haven't been able to get GitHub OAuth to work.

The OAuth was not working because `Access-Control-Allow-Origin` wasn't set on the server-side, I have fixed that now. It should be working. :)

2020-06-21 06:06 UTC, ramantehlan commented on applications/web/pages/p/[...params].tsx
> +              <Editor
I have added a TODO for it. We will eventually render notebooks differently using the nteract core lib.

2020-06-21 06:10 UTC, ramantehlan commented on applications/web/pages/p/[...params].tsx
> +import Editor from 'react-simple-code-editor';
I did use @nteract/monaco-editor, but it was raising a known issue. Next.js doesn't support css import from node_modules, as mentioned [here](https://github.com/vercel/next.js/blob/master/errors/css-npm.md). 
![gscreenshot_2020-06-21-113053](https://user-images.githubusercontent.com/29037312/85218000-cf7fd280-b3b3-11ea-8bf5-eaaa53d15aff.png)

2020-06-21 06:28 UTC, ramantehlan commented on applications/web/pages/util.js
> +function getFilePath(params){
I agree. I have moved the functions to the main page.

2020-06-28 03:46 UTC, ramantehlan commented
I have left some inline TODOs, which we can do in phase-2. All the TODOs are tasks broken down to achieve the above pending work. I have also added other important tasks to the list.

2020-07-02 02:16 UTC, captainsafia requested changes
Looks good overall. Key pieces of feedback include:

- Using CSS variables instead of hard-coded values where possible
- Cleaning up the formatting on files
- Ensuring that we have notebook rendering as part of this PR

2020-07-02 02:16 UTC, captainsafia commented on applications/web/components/BinderMenu.tsx
> +    border-bottom:0px solid #d1e3dd;
For consistency with the rest of the nteract UX, considering using the CSS variables that are included in @nteract/styles.

2020-07-02 02:16 UTC, captainsafia commented on applications/web/components/Button.tsx
> +outline:none;
Nit: Indentation.

2020-07-02 02:16 UTC, captainsafia commented on applications/web/components/BinderMenu.tsx
> +BinderMenu.defaultProps = {
Maybe the default values should be for the nteract/examples here?

2020-07-02 02:16 UTC, captainsafia commented on applications/web/package.json
> +    "react-simple-code-editor": "^0.11.0",
If Monaco is giving us trouble here, I'd prefer we use the @nteract/editor package instead of introducing another editor dependency into the project.

2020-07-02 02:16 UTC, captainsafia commented on applications/web/pages/auth/index.tsx
> +                <p>Go back to the application and click on the 'Connect to Github' button again. You can close this window now.</p>
We discussed this during our 1:1 but you can store the token in local storage and listen for changes in local storage and update the UI without having users double click.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged

2020-07-14 10:11 UTC, ramantehlan commented on applications/web/pages/auth/index.tsx
> +                <p>Go back to the application and click on the 'Connect to Github' button again. You can close this window now.</p>
Done. :)

2020-07-15 19:04 UTC, ramantehlan commented on applications/web/pages/p/[...params].tsx
> +import Editor from 'react-simple-code-editor';
I tried following along this(below link) fix for it, but couldn't. Leaving the link here to come back to it later.

https://dev.to/swyx/how-to-add-monaco-editor-to-a-next-js-app-ha3

2020-07-16 18:06 UTC, ramantehlan commented on applications/web/components/Button.tsx
> +outline:none;
Thank you for pointing it out. :)

 I have created a TODO for it and will do it in the end, using a VS Code or Atom extension for the whole project.

2020-07-25 20:41 UTC, merged