Update changelog to include myths changes and new configuration component
nteract/archived-desktop-app pull request #5172
Opened 2020-06-22 07:40 UTC by CrystallineCat

I hope the `mythic-configuration` changelog entry can also serve as a migration guide. @captainsafia please tell me if I'm missing anything and I'll add it.

2020-06-24 00:17 UTC, captainsafia requested changes
Coolio! Left a few comments inline.

@willingc @emeeks Can you provide your perspective on this as well?

2020-06-24 00:17 UTC, captainsafia commented on changelogs/current_changelog.md
> +- Dispatch the return value of `setConfigFile(<path>)` to make it load/write/watch a config file instead.
Can we add a bullet here that describes how to configure the myth in the Redux store?

2020-06-24 00:17 UTC, captainsafia commented on changelogs/current_changelog.md
> +- New mythic package, will setup a transient in-memory configuration store per default. ([PR#5137](https://github.com/nteract/nteract/pull/5137))
Can we add a note on how to set up other configuration stores for those who might be interested?

2020-06-24 02:26 UTC, willingc reviewed
Thanks @CrystallineCat. I appreciate your work on this. I'm new to using myths so my comments are on clarifying text that wasn't clear to me. :cake:

2020-06-24 02:26 UTC, willingc commented on changelogs/current_changelog.md
> +- New mythic package, will setup a transient in-memory configuration store per default. ([PR#5137](https://github.com/nteract/nteract/pull/5137))
I'm not clear on what `per default` means. Is it setting up a store for each default configuration setting?

2020-06-24 02:26 UTC, willingc commented on changelogs/current_changelog.md
> +- Changed API somewhat, see `README.md` for details. ([PR#5106](https://github.com/nteract/nteract/pull/5106))
Are the changes `thenDispatch` and `andAlso`?

2020-06-25 17:07 UTC, CrystallineCat commented on changelogs/current_changelog.md
> +- New mythic package, will setup a transient in-memory configuration store per default. ([PR#5137](https://github.com/nteract/nteract/pull/5137))
It means if there is no other backend configured, it'll default to in-memory. I've clarified this in the doc.

2020-06-25 17:08 UTC, CrystallineCat commented on changelogs/current_changelog.md
> +- Changed API somewhat, see `README.md` for details. ([PR#5106](https://github.com/nteract/nteract/pull/5106))
Those are the the main changes, yes.

2020-06-25 17:12 UTC, CrystallineCat commented
Thanks for the comments, @captainsafia and @willingc! I updated the documentation.

2020-06-25 18:05 UTC, willingc approved these changes
Thanks for the additions @CrystallineCat :smile:

2020-06-26 14:11 UTC, merged