Documentation
nteract/archived-desktop-app pull request #845
Opened 2016-09-27 23:24 UTC by jdetle

This code attempts to document the work done in the execute epic. This is something that should be seriously reviewed because there are certainly mistakes abound since its fairly rxJS heavy code.

2016-09-27 23:26 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * @param {Object} msg - Blank message.
`msg` isn't blank.

2016-09-27 23:27 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * Reads a payloadStream and inspects it for pager actions dispatched upon
Should be pager data, not pager actions.

2016-09-27 23:36 UTC, captainsafia requested changes

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * Pager actions.
Same as above. Should be pager data.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * Insert a create source update action into a group of messages.
It actually dispatches an action to update the source of a cell if the kernel has requested so by setting `replace` to true.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * Insert a create cell after action into a group of messages.
I would use dispatches instead of inserts here as well.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * This code updates the cell numbering on the frontend.
Dispatches an action to update the execution count.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * to the execution of a cell in the kernel.
It returns an observable with a stream of events that need to happen **after** a cell has been executed.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * @param {Object} cellMessages - Nessages to receive updates.
`cellMessages` is an Observable not an Object.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * @param {Object} cellMessages - Set of sent cell messages.
Same as above. `cellMessages` is an Observable.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * @return {Object} cellMessages - Set of updated cell messages.
The output is also an Observable.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * @return {Object} cellMessages - Updated messages.
This is also an Observable.

2016-09-27 23:36 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * @return {Object} updated_outputs -
Both `setInputStream` and the returned value are streams.

2016-09-27 23:37 UTC, jdetle commented on src/notebook/epics/execute.js
> + * @return {Object} cellMessages - Set of updated cell messages.
Thanks, I was confused about this, does this come from enchannel?

2016-09-27 23:43 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * @return {Object} cellMessages - Set of updated cell messages.
Ish? All of the Observables in execute functions are subsets of the data that is returned by the shell or iopub subjects which are defined in enchannel-zmq-backend. If you read the code you'll notice that in lines 87 through 101.

2016-09-27 23:44 UTC, jdetle commented on src/notebook/epics/execute.js
> + * @return {Object} updated_outputs -
This is totally still a huge pain point for me. http://jsfiddle.net/staltz/8jFJH/48/ Playing with this code leaves me to believe all streams are observables. Should I distinguish streams vs observables in the docs or are the synonymous?

2016-09-27 23:51 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * @return {Object} updated_outputs -
IMO, a stream is a general term for a set of events that happen through time. In can be used in computational contexts that don't relate to reactive programming at all. An Observable is a wrapper around a stream that gives you additional functionality like merging and filtering. In our specific case, we are returning streams in the form of Observables in all our code so you need to write.
```
@param {Rx.Observable} setInputStream 
```

@rgbkrk might have better ideas since he works with RxJS all day.

2016-09-27 23:54 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * @param {Object} msg - Blank message.
"Message that has content which can be converted to nbformat (e.g. display_data)"

2016-09-27 23:55 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * Insert a create source update action into a group of messages.
I wouldn't use the word dispatch here, since `dispatch` goes with redux. Maybe "emits"?

2016-09-27 23:56 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * @return {Object} updated_outputs -
Let's call them Observables since that's what they are. The name stream I started using to make the variable make sense.

2016-09-27 23:56 UTC, captainsafia commented on src/notebook/epics/execute.js
> + * Insert a create source update action into a group of messages.
I think it would help to show that this connects to Redux dispatching eventually, hence the word use.

2016-09-27 23:56 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * @return {Object} updated_outputs -
Return type can probably be:

```
@return {Observable<Action>}
```

2016-09-28 00:01 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * @return {Object} cellMessages - Set of updated cell messages.
`iopub` and `shell` are both Subjects, created like this:

```
/**
 * Helper function for creating a subject from a socket
 * @param {jmp.Socket} socket the jmp/zmq socket connection to a kernel channel
 * @return {Rx.Subject} subject for sending and receiving messages to kernels
 */
export function createSubject(socket) {
  const subj = Subject.create(createSubscriber(socket),
                              createObservable(socket));
  return subj;
}
```

When you chain off of it (not `shell.send`), you're applying functions to create new observables/streams.

```js
iopub.filter(x => x.header.msg_type === 'awesome') // Rx.Observable
```

2016-09-28 00:03 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * to the execution of a cell in the kernel.
Complete mind-shift: "Observe all the reactions to running code for cell with id"

2016-09-28 00:03 UTC, jdetle commented on src/notebook/epics/execute.js
> + * Insert a create source update action into a group of messages.
"Emits a `createSourceUpdateAction` to update the source of a cell if the kernel has requested so by setting replace to true. This is eventually dispatched as a redux action."

2016-09-28 00:05 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * Insert a create source update action into a group of messages.
"to be dispatched as a redux action" - since there is zero dispatch - it's intended to be consumed by the user via redux-observable.

2016-09-28 00:08 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * Insert a create source update action into a group of messages.
Hopefully this doesn't dilute this too much - these observables can still be used with @philpl's https://github.com/philpl/redux-fluorine since they emit actions.

2016-09-28 00:41 UTC, jdetle commented on src/notebook/epics/execute.js
> + * @return {Object} updated_outputs -
Observable<Action> doesn't get highlighted in my current state of atom. Okay if I just default to Observable?

2016-09-28 01:17 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * @param {Observable<Actions>} cellMessages - Messages to receive create cell status action.
This should be `Observable<jmp.Message>` or `jupyter.Message` if you prefer.

2016-09-28 01:29 UTC, jdetle commented on src/notebook/epics/execute.js
> + * @param {Observable<Actions>} cellMessages - Messages to receive create cell status action.
Same with line 160 I presume?

2016-09-28 01:37 UTC, rgbkrk approved these changes

2016-09-28 01:42 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * @param {Observable<Actions>} cellMessages - Messages to receive create cell status action.
Looks like you've handled it already. :smile:

2016-09-28 01:42 UTC, merged

2016-09-28 01:43 UTC, rgbkrk commented on src/notebook/epics/execute.js
> + * http://jupyter-client.readthedocs.io/en/latest/messaging.html
This should probably have

```
@see https://nbformat.readthedocs.io/en/latest/format_description.html#code-cell-outputs
```