Add Google Analytics tracking
nteract/archived-desktop-app pull request #876
Opened 2016-10-01 02:17 UTC by captainsafia

Setting us up with tracking so we can get some cool stats.

Shamefully, this slows down launch time quite a bit.

Also, it asks the user whether or not they want to be tracked at every launch.

2016-10-01 02:32 UTC, rgbkrk requested changes

2016-10-01 02:32 UTC, rgbkrk commented on src/main/launch.js
> +      index = path.join(__dirname, '..', '..', 'static', 'index-with-ga.html');
You can do all of the analytics loading as part of a dynamic epic or another way with the redux state tree, coordinating using `ipc` on launch. Then we don't have to duplicate all the code in the html below _and_ startup can be faster.

2016-10-03 18:11 UTC, rgbkrk commented on src/main/index.js
> +  .skip(1)
Does this fire more than once then?

2016-10-03 18:23 UTC, captainsafia commented
> Does this fire more than once then?

Yeah, the skip is so that it doesn't run this on the initial splash window. But as before, it runs every time the user opens a new notebook.

I'm trying to see if there is some combination of operators wherein I can say "If this is the second time this event is triggered, show the dialog box and then load Google Analytics into the webpage. For all future emissions, just load GA into the webpage."

2016-10-03 18:29 UTC, rgbkrk commented
> I'm trying to see if there is some combination of operators wherein I can say "If this is the second time this event is triggered, show the dialog box and then load Google Analytics into the webpage. For all future emissions, just load GA into the webpage."

I'd make this a global "configuration" thing, just like our theme setup - rely on `electron-json-storage` for now until we have a main thread config system. The config for this can likely be:

```json
{
  "hasBeenPrompted": true,
  "send-metrics": true,
}
```

then again, you may only need the one field (if this wasn't set up, then we can assume a dialog):

```json
{
  "send-metrics": true,
}
```

2016-10-04 00:43 UTC, captainsafia commented
Closing in favor of another PR with the config approach.

2016-10-04 00:43 UTC, closed without merging