Problem: https://github.com/nteract/nteract/issues/887
nteract/archived-desktop-app pull request #890
Opened 2016-10-03 05:33 UTC by estevanjantsk

Added Flow typings to status-bar component 👍 .

2016-10-03 05:35 UTC, jdetle commented
@estevanjantsk What happens when you run `npm run flow`? I was having trouble getting it working on my machine this morning.

2016-10-03 05:42 UTC, estevanjantsk commented
I tested here with "npm run-script flow" and runned ok. It gives some errors with node_modules, but I think if I put 
```
[ignore]
.*/node_modules/.*
```
in .flowconfig it will ignore all errors =)

2016-10-03 05:50 UTC, captainsafia requested changes

2016-10-03 05:50 UTC, captainsafia commented on .flowconfig
> +.*node_modules/fbjs.*
Can you add the `test` and `static` folders to this as well?

Alternatively, I think you can move this file to `src/` to have it run flow on only that subdirectory.

2016-10-03 05:50 UTC, captainsafia commented on src/notebook/components/status-bar.js
> +  props: Props;
Can you move the `props` object into the component like this? The linter gets mad at this right now.

```
props: {
...
}
```

2016-10-03 05:50 UTC, captainsafia commented on package.json
> +    "flow": "flow; test $? -eq 0 -o $? -eq 2"
Do you think you can set up Flow with Babel as well? If not, no worries.

2016-10-03 05:51 UTC, captainsafia commented
Thanks for this awesome pull request, Estevan! Welcome to the nteract community! 🎉 

I placed a couple of comments in line for you to take a look at. Let me know if you have any questions about those comments. 😄

2016-10-03 05:53 UTC, jdetle commented
_psssst_ You're also welcome to chat on http://slack.nteract.in/

2016-10-03 06:01 UTC, estevanjantsk commented on src/notebook/components/status-bar.js
> +  props: Props;
Nice, I thought it would be good practice put with type Props. Im gonna change o/.

2016-10-03 06:02 UTC, captainsafia commented on src/notebook/components/status-bar.js
> +  props: Props;
Yeah, I definitely hear you on that. I think once we've added Flow to all our components we'll make the appropriate updates to our linting setup. Good foresight!

2016-10-03 06:06 UTC, estevanjantsk commented on package.json
> +    "flow": "flow; test $? -eq 0 -o $? -eq 2"
```
$> npm install -g babel-cli
$> npm install --save-dev babel-plugin-transform-flow-strip-types
$> echo '{"plugins": ["transform-flow-strip-types"]}' > .babelrc
```

👍

2016-10-03 06:20 UTC, estevanjantsk commented on .flowconfig
> +.*node_modules/fbjs.*
ignore these two folders: test and static?

2016-10-03 06:21 UTC, captainsafia commented on .flowconfig
> +.*node_modules/fbjs.*
Yes! 👍

2016-10-03 07:07 UTC, captainsafia commented
Great! One last thing, we follow the [conventional changelog standard](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md) for structuring our commit messages.

Do you know how to rebase your PR and reword your commit messages or would you like us to squash the commits and create a single commit that adheres to the standard?

2016-10-03 07:17 UTC, estevanjantsk commented
@captainsafia Sorry but I don't know how to do that =( (rebase your PR and reword your commit messages), may you fix that for me please?

2016-10-03 07:22 UTC, jdetle commented
@estevanjantsk, do you use a command line text-editor like vim?

2016-10-03 07:23 UTC, captainsafia commented
> @captainsafia Sorry but I don't know how to do that =( (rebase your PR and reword your commit messages), may you fix that for me please?

No problem, Estevan! I'll make the appropriate changes on my end. Thank you so much for submitting this pull request!

2016-10-03 07:43 UTC, captainsafia commented
@estevanjantsk: Can you give me push access to your fork of this repository? This will allow me to make the changes necessary. To do this you will need to.

1. Go to your fork of the nteract repository.
2. Click "Settings" in the top bar of the repository.
3. Click the "Collaborators" tab and add my username to as a collaborator.

Thanks!

2016-10-03 07:43 UTC, captainsafia approved these changes

2016-10-03 07:55 UTC, estevanjantsk commented
@captainsafia added o/!
@jdetle I use atom as my text editor. I know, I kno, I have to go to the dark side and use vim haha. Thanks for the tip with the git.

I'll join the nteract slack, @captainsafia and @jdetle, you both are awesome =DDD!!!

2016-10-03 08:10 UTC, jdetle commented
@estevanjantsk I actually use both! ¯\_(ツ)_/¯ I look forward to seeing more PRs in the future!

2016-10-03 15:24 UTC, merged

2016-10-03 16:42 UTC, rgbkrk commented
Thanks for kicking off our `flow` setup. :D

2016-10-04 02:35 UTC, estevanjantsk commented
@rgbkrk You're welcome o>!