WIP: Create a json transform component
nteract/archived-desktop-app pull request #955
Opened 2016-10-08 22:36 UTC by aleury

https://github.com/nteract/nteract/issues/931. 

I don't intend this to be merged at the moment.

2016-10-08 22:41 UTC, aleury commented
If you execute a cell a with the following
```python
person = { 'name': 'John Smith' }
person
```
the mime type of the result is `text/plain`, so in order to display it as a json tree, I put a check in `richestMimetype` to check if it can be converted to valid json and if so, return the `application/json` mime type.

2016-10-08 22:42 UTC, rgbkrk commented
From Python, here's how you do custom raw mimetypes:

```python
IPython.display.display({'application/json': data}, raw=True)
```

2016-10-08 22:43 UTC, rgbkrk commented on src/notebook/components/cell/display-area/richest-mime.js
> +    const data = this.props.bundle.get('text/plain');
We definitely don't want to case here, it needs to come in as `application/json`.

2016-10-08 22:45 UTC, rgbkrk requested changes
Use either the raw way I outlined in an earlier comment or use:

```
import IPython.display
IPython.display.JSON({"a": 2})
```

To try out the JSON. It should be a direct mapping, no special casing with `text/plain`.

2016-10-08 22:50 UTC, aleury commented
Ah! Okay, that makes sense. I'll try that. Thanks!

2016-10-09 02:00 UTC, aleury commented
Updated the PR and added a couple of tests.

2016-10-09 02:25 UTC, rgbkrk approved these changes

2016-10-09 02:25 UTC, rgbkrk commented on src/notebook/components/transforms/json.js
> +function getTheme(themeName) {
Wow, this was definitely some next level work here. Stellar.

2016-10-09 02:25 UTC, rgbkrk commented on src/notebook/components/transforms/json.js
> +const defaultTheme = {
Somehow we're going to need to map to our CSS variables so that styling happens via CSS, even if translated here. Not for this PR though, we can figure out an approach later.

2016-10-09 02:25 UTC, rgbkrk commented on src/notebook/components/transforms/json.js
> +    return true;
This should likely be `false` right now, or it needs to check on the theme. `this.props.data` won't change (because of how the Jupyter messages currently work).

2016-10-09 02:26 UTC, rgbkrk commented
Any screenshots?

2016-10-09 02:29 UTC, aleury commented on src/notebook/components/transforms/json.js
> +const defaultTheme = {
That's what I was thinking. I just attempted to come up with something that looked halfway decent for the time being.

2016-10-09 02:30 UTC, rgbkrk commented on src/notebook/components/transforms/json.js
> +const defaultTheme = {
According to their docs, these are also class names. I'm happy to play with that after we merge though.

2016-10-09 02:36 UTC, aleury commented
<img width="743" alt="screen shot 2016-10-08 at 10 33 59 pm" src="https://cloud.githubusercontent.com/assets/1060558/19217383/89c2a2a8-8da7-11e6-8865-7af821f4b713.png">
<img width="720" alt="screen shot 2016-10-08 at 10 34 26 pm" src="https://cloud.githubusercontent.com/assets/1060558/19217385/8d178aae-8da7-11e6-8102-a27096262c51.png">
<img width="730" alt="screen shot 2016-10-08 at 10 34 45 pm" src="https://cloud.githubusercontent.com/assets/1060558/19217387/93d5fb82-8da7-11e6-8a21-ef612ef50cec.png">
<img width="720" alt="screen shot 2016-10-08 at 10 34 26 pm" src="https://cloud.githubusercontent.com/assets/1060558/19217388/95b069e2-8da7-11e6-86ef-d11c16590ca7.png">

2016-10-09 02:36 UTC, rgbkrk commented
Lookin' excellent.

2016-10-09 02:37 UTC, aleury commented on src/notebook/components/transforms/json.js
> +const defaultTheme = {
Sounds good! I'll look over the docs some more.

2016-10-09 02:38 UTC, rgbkrk commented
Just take the WIP off the title when you think you're ready. I think we're fine to iterate on this one after. Up to you, this is looking solid.

2016-10-09 02:54 UTC, aleury commented
Okay, I updated `componentShouldUpdate` and it should be ready to go! Thanks!

2016-10-09 02:57 UTC, merged

2016-10-09 02:57 UTC, rgbkrk commented
Thanks!

2016-10-09 02:59 UTC, rgbkrk commented
This is quite good, thank you!

![screen shot 2016-10-08 at 10 59 06 pm](https://cloud.githubusercontent.com/assets/836375/19217520/db6e4fc8-8daa-11e6-98fb-266c15466a65.png)

2016-10-09 03:00 UTC, aleury commented
Any time! 😃