[WIP] feat(Display): Add scrollable display
nteract/archived-desktop-app pull request #972
Opened 2016-10-10 20:08 UTC by captainsafia

I still have to clean up the tests.

2016-10-11 03:47 UTC, rgbkrk commented
Excited for this one.

2016-10-13 17:09 UTC, captainsafia commented
OK. This should be good for review.

![nteract_expanded](https://cloud.githubusercontent.com/assets/1857993/19358969/b74613c4-913d-11e6-9264-606830a5b0cc.gif)

I noticed that we weren't using enzyme in the tests for Display. I assume this is a consequence of bringing the DisplayArea in. Do we want to move the tests over to using enzyme so it is consistent with the rest of the code base?

2016-10-13 17:12 UTC, rgbkrk commented
> I noticed that we weren't using enzyme in the tests for Display. I assume this is a consequence of bringing the DisplayArea in. Do we want to move the tests over to using enzyme so it is consistent with the rest of the code base?

Yeah, that's a consequence of bringing DisplayArea in. We should definitely switch to `enzyme`.

2016-10-13 17:37 UTC, rgbkrk requested changes

2016-10-13 17:37 UTC, rgbkrk commented on src/notebook/actions.js
> +  };
This one isn't covered by the tests and should be a quick and easy action creator test.

2016-10-13 17:37 UTC, rgbkrk commented on src/notebook/components/cell/toolbar.js
> +    this.context.store.dispatch(toggleOutputExpansion(this.props.id));
Use `enzyme`'s instance to get the React Element then run this function.

2016-10-13 17:37 UTC, rgbkrk commented on src/notebook/reducers/document.js
> +      !cells.getIn([id, 'outputExpanded'])));
This looks pretty testable as a reducer.

2016-10-13 17:38 UTC, captainsafia commented
> Yeah, that's a consequence of bringing DisplayArea in. We should definitely switch to enzyme.

Yep. I can address that and the coverage drop in another PR.

2016-10-13 17:38 UTC, rgbkrk commented on src/notebook/components/cell/display-area/display.js
> +  };
This is pretty awesome. I wonder if we could do something where it doesn't scroll unless you focus on it too.

2016-10-13 18:06 UTC, merged